// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Aquakulturen, Bereich 2 - Weichtiere mit Betriebsstammdaten (Abfrage, nur aktuell)
    /// </summary>
    [Entity("AQ_B2_W_BD")]
    public class AQ_B2_W_BD
    {
        /// <summary>
        /// Gets or sets the value of "Argentinische Auster (Ostrea puelchana)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_001")]
        public int? AQ_B2A_001 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Asiatische Auster (O. denselammellosa)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_002")]
        public int? AQ_B2A_002 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Australische Flachauster (Ostrea angasi)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_003")]
        public int? AQ_B2A_003 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Chilenische Flachauster (Ostrea chilensis)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_004")]
        public int? AQ_B2A_004 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Europäische Auster (Ostrea edulis)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_005")]
        public int? AQ_B2A_005 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Miesmuschel (Mytilus edulis)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_006")]
        public int? AQ_B2A_006 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Mittelmeermiesmuschel (Mytilus galloprovincialis)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_007")]
        public int? AQ_B2A_007 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Westamerikanische Auster (Ostrea conchaphila)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_008")]
        public int? AQ_B2A_008 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gegitterte Venusmuschel (Ruditapes decussatus)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_010")]
        public int? AQ_B2A_010 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Goldene Teppichmuschel (Venerupis aurea)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_014")]
        public int? AQ_B2A_014 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Große Pilgermuschel (Pecten maximus)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_015")]
        public int? AQ_B2A_015 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Herzmuschel (Cerastoderma edule)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_016")]
        public int? AQ_B2A_016 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Japanische Teppichmuschel (Ruditapes philippinarum)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_017")]
        public int? AQ_B2A_017 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Japanische Venusmuschel (Meretrix lusoria)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_018")]
        public int? AQ_B2A_018 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kleine Teppichmuschel (Venerupis pullastra)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_019")]
        public int? AQ_B2A_019 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Mittelmeer-Dreiecksmuschel (Donax trunculus)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_020")]
        public int? AQ_B2A_020 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nördliche Venusmuschel (Mercenaria mercenaria)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_022")]
        public int? AQ_B2A_022 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Raue Venusmuschel (Venus verrucosa)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_025")]
        public int? AQ_B2A_025 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Sandklaffmuschel (Mya arenaria)".
        /// </summary>
        /// <remarks>
        /// ist diese Weichtierart vorhanden
        /// </remarks>
        [Column("AQ_B2A_026")]
        public int? AQ_B2A_026 { get; set; }

        /// <summary>
        /// Gets or sets the value of "BO empfängliche Tierarten".
        /// </summary>
        /// <remarks>
        /// werden Tieraten gehalten die empfänglich sind für Bonamia ostrea
        /// </remarks>
        [Column("AQ_B2E_BO")]
        public int? AQ_B2E_BO { get; set; }

        /// <summary>
        /// Gets or sets the value of "MR empfängliche Tierarten".
        /// </summary>
        /// <remarks>
        /// werden Tieraten gehalten die empfänglich sind für Marteilia refingens
        /// </remarks>
        [Column("AQ_B2E_MR")]
        public int? AQ_B2E_MR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Offene Anlage".
        /// </summary>
        /// <remarks>
        /// ist diese Haltungsform für Bereich 2 - Weichtiere vorhanden
        /// </remarks>
        [Column("AQ_B2H_001")]
        public int? AQ_B2H_001 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kreislaufanlage (geschlossen)".
        /// </summary>
        /// <remarks>
        /// ist diese Haltungsform für Bereich 2 - Weichtiere vorhanden
        /// </remarks>
        [Column("AQ_B2H_002")]
        public int? AQ_B2H_002 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Versandzentrum, Reinigungszentrum".
        /// </summary>
        /// <remarks>
        /// ist diese Haltungsform für Bereich 2 - Weichtiere vorhanden
        /// </remarks>
        [Column("AQ_B2H_003")]
        public int? AQ_B2H_003 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Weichtierzuchtgebiet".
        /// </summary>
        /// <remarks>
        /// ist diese Haltungsform für Bereich 2 - Weichtiere vorhanden
        /// </remarks>
        [Column("AQ_B2H_004")]
        public int? AQ_B2H_004 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Forschungseinrichtung (Ordner: sonst. BA mit Nutztieren)".
        /// </summary>
        /// <remarks>
        /// ist diese Haltungsform für Bereich 2 - Weichtiere vorhanden
        /// </remarks>
        [Column("AQ_B2H_005")]
        public int? AQ_B2H_005 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Quarantänestation".
        /// </summary>
        /// <remarks>
        /// ist diese Haltungsform für Bereich 2 - Weichtiere vorhanden
        /// </remarks>
        [Column("AQ_B2H_006")]
        public int? AQ_B2H_006 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Erbrütung (Vermehrungsbetrieb)".
        /// </summary>
        /// <remarks>
        /// ist diese Nutzungsrichtung für Bereich 2 - Weichtiere vorhanden
        /// </remarks>
        [Column("AQ_B2N_001")]
        public int? AQ_B2N_001 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Muschelaufzucht".
        /// </summary>
        /// <remarks>
        /// ist diese Nutzungsrichtung für Bereich 2 - Weichtiere vorhanden
        /// </remarks>
        [Column("AQ_B2N_002")]
        public int? AQ_B2N_002 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Mastbetrieb".
        /// </summary>
        /// <remarks>
        /// ist diese Nutzungsrichtung für Bereich 2 - Weichtiere vorhanden
        /// </remarks>
        [Column("AQ_B2N_003")]
        public int? AQ_B2N_003 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bonamia ostrea".
        /// </summary>
        /// <remarks>
        /// Seuchenstatus (Kategorie (I-V) der genannten Seuche, Bereich 2 - Weichtiere
        /// </remarks>
        [Column("AQ_B2S_BO")]
        public int? AQ_B2S_BO { get; set; }

        /// <summary>
        /// Gets or sets the value of "Marteilia refingens".
        /// </summary>
        /// <remarks>
        /// Seuchenstatus (Kategorie (I-V) der genannten Seuche, Bereich 2 - Weichtiere
        /// </remarks>
        [Column("AQ_B2S_MR")]
        public int? AQ_B2S_MR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Sonstige Seuchen".
        /// </summary>
        /// <remarks>
        /// Seuchenstatus (Kategorie (I-V) der genannten Seuche, Bereich 2 - Weichtiere
        /// </remarks>
        [Column("AQ_B2S_SON")]
        public int? AQ_B2S_SON { get; set; }

        /// <summary>
        /// Gets or sets the value of "BO Überträger Tierarten".
        /// </summary>
        /// <remarks>
        /// werden Tieraten gehalten die Überträger sind für Bonamia ostrea
        /// </remarks>
        [Column("AQ_B2T_BO")]
        public int? AQ_B2T_BO { get; set; }

        /// <summary>
        /// Gets or sets the value of "MR Überträger Tierarten".
        /// </summary>
        /// <remarks>
        /// werden Tieraten gehalten die Überträger sind für Marteilia refingens
        /// </remarks>
        [Column("AQ_B2T_MR")]
        public int? AQ_B2T_MR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betrieb unterliegt genehmigten Tilgungsprogramm bzw. Bekämpfungsmaßnahmen".
        /// </summary>
        /// <remarks>
        /// gemäß Kapitel V Abschnitt 3,4,5 oder 6 der RL 2006/88/EG, Bereich 2 - Weichtiere
        /// </remarks>
        [Column("AQ_B2X_TIP")]
        public int? AQ_B2X_TIP { get; set; }

        /// <summary>
        /// Gets or sets the value of "Endezeitpunkt Registrierungsdaten Aquakulturbetrieb".
        /// </summary>
        /// <remarks>
        /// Endes der fachlichen Gültigkeit (identisch zu nächstem Beginn, oder 31.12.2100 wenn aktuell)
        /// </remarks>
        [Column("AQ_BIS")]
        [Required]
        public DateTime? AQ_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Beginnzeitpunkt Registrierungsdaten Aquakulturbetrieb".
        /// </summary>
        /// <remarks>
        /// Beginns der fachlichen Gültigkeit
        /// </remarks>
        [Column("AQ_VON")]
        [Required]
        public DateTime? AQ_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ortsteil".
        /// </summary>
        /// <remarks>
        /// Ortsteil wenn erforderlich
        /// </remarks>
        [Column("ORTSTEIL")]
        public string? ORTSTEIL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ort".
        /// </summary>
        /// <remarks>
        /// Ort
        /// </remarks>
        [Column("ORT")]
        public string? ORT { get; set; }

        /// <summary>
        /// Gets or sets the value of "UTM Geokoordinate Rechtswert".
        /// </summary>
        /// <remarks>
        /// bezogen auf ETRS89, i.d.R. im natürlichen Streifen 32 oder 33
        /// </remarks>
        [Column("GEO_UTM_R")]
        public decimal? GEO_UTM_R { get; set; }

        /// <summary>
        /// Gets or sets the value of "UTM Geokoordinate Hochwert".
        /// </summary>
        /// <remarks>
        /// bezogen auf ETRS89, i.d.R. im natürlichen Streifen 32 oder 33
        /// </remarks>
        [Column("GEO_UTM_H")]
        public decimal? GEO_UTM_H { get; set; }

        /// <summary>
        /// Gets or sets the value of "GPS Geokoordinate Y-Wert".
        /// </summary>
        /// <remarks>
        /// positiv Nord-Wert (N), negativ Süd-Wert (S), in Grad mit Dezimalstellen (nicht Minuten, Sekunden)
        /// </remarks>
        [Column("GEO_GPS_Y")]
        public decimal? GEO_GPS_Y { get; set; }

        /// <summary>
        /// Gets or sets the value of "GPS Geokoordinate X-Wert".
        /// </summary>
        /// <remarks>
        /// positiv Ost-Wert (E), negativ West-Wert (W), in Grad mit Dezimalstellen (nicht Minuten, Sekunden)
        /// </remarks>
        [Column("GEO_GPS_X")]
        public decimal? GEO_GPS_X { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nutzungsrichtung".
        /// </summary>
        [Column("AQ_B_NUTZ")]
        public string? AQ_B_NUTZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsbezeichnung (zusätzlich)".
        /// </summary>
        [Column("AQ_B_NAME2")]
        public string? AQ_B_NAME2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsbezeichnung".
        /// </summary>
        [Column("AQ_B_NAME")]
        public string? AQ_B_NAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Haltungsform".
        /// </summary>
        [Column("AQ_B_HALT")]
        public string? AQ_B_HALT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Strasse Nr".
        /// </summary>
        /// <remarks>
        /// Straße und Hausnummer
        /// </remarks>
        [Column("STR_NR")]
        public string? STR_NR { get; set; }

        /// <summary>
        /// Gets or sets the value of "PLZ".
        /// </summary>
        /// <remarks>
        /// Postleitzahl, ggf. internat. ohne Staat
        /// </remarks>
        [Column("PLZ")]
        public string? PLZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Aquakulturbetrieb im anerkannten Schutzgebiet j/n".
        /// </summary>
        /// <remarks>
        /// Aquakulturbetrieb im anerkannten Schutzgebiet j/n (gem. §10 FSVO)
        /// </remarks>
        [Column("AQ_SCHUTZG")]
        public int? AQ_SCHUTZG { get; set; }

        /// <summary>
        /// Gets or sets the value of "genehmigter/registrierter Aquakulturbetrieb".
        /// </summary>
        [Column("AQ_REG_GEN")]
        public int? AQ_REG_GEN { get; set; }

    }
}
