// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// BSE-Test Kontakt+Stammdaten (View aus BSETKON und BTR_D)
    /// </summary>
    [Entity("BSETKONX")]
    public class BSETKONX
    {
        /// <summary>
        /// Gets or sets the value of "Fax".
        /// </summary>
        /// <remarks>
        /// Fax-Anschluß
        /// </remarks>
        [Column("FAX")]
        public string? FAX { get; set; }

        /// <summary>
        /// Gets or sets the value of "E-Mail".
        /// </summary>
        /// <remarks>
        /// E-Mailadresse
        /// </remarks>
        [Column("EMAIL")]
        public string? EMAIL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betrieb gültig von".
        /// </summary>
        /// <remarks>
        /// Timestamp ab wann der Satz fachlich gilt
        /// </remarks>
        [Column("DBET_VON")]
        public DateTime? DBET_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betrieb gültig bis".
        /// </summary>
        /// <remarks>
        /// fachlich gültig bis oder aktuell (31.12.2100)
        /// </remarks>
        [Column("DBET_BIS")]
        public DateTime? DBET_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Sendeprofil".
        /// </summary>
        /// <remarks>
        /// Versendewunsch des Faxempfängers und Sendeprofil des Ergebnissatzes
        /// </remarks>
        [Column("BSET_SEND")]
        public int? BSET_SEND { get; set; }

        /// <summary>
        /// Gets or sets the value of "PLZ".
        /// </summary>
        /// <remarks>
        /// Postleitzahl, ggf. internat. ohne Staat
        /// </remarks>
        [Column("PLZ")]
        public string? PLZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Postfach-PLZ".
        /// </summary>
        /// <remarks>
        /// Postfach-PLZ, ggf. internat. ohne Staat
        /// </remarks>
        [Column("PF_PLZ")]
        public string? PF_PLZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Postfach-Nr".
        /// </summary>
        /// <remarks>
        /// Nummer des Postfachs
        /// </remarks>
        [Column("PF_NR")]
        public string? PF_NR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Firma/Organisation".
        /// </summary>
        /// <remarks>
        /// Firma bzw. Organisation
        /// </remarks>
        [Column("FIRMA")]
        public string? FIRMA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Telefon".
        /// </summary>
        /// <remarks>
        /// Telefon-Anschluß
        /// </remarks>
        [Column("TELEFON")]
        public string? TELEFON { get; set; }

        /// <summary>
        /// Gets or sets the value of "gespeichert (Teil A)".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information im Teil A technisch gültig ist
        /// </remarks>
        [Column("SYS_VON_A")]
        public DateTime? SYS_VON_A { get; set; }

        /// <summary>
        /// Gets or sets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Satzstatus".
        /// </summary>
        /// <remarks>
        /// Systemstatus des Satzes
        /// </remarks>
        [Column("SYS_STAT")]
        public int? SYS_STAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ortsteil".
        /// </summary>
        /// <remarks>
        /// Ortsteil wenn erforderlich
        /// </remarks>
        [Column("ORTSTEIL")]
        public string? ORTSTEIL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ort".
        /// </summary>
        /// <remarks>
        /// Ort
        /// </remarks>
        [Column("ORT")]
        public string? ORT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Name 2.Zeile".
        /// </summary>
        /// <remarks>
        /// 2.Namenszeile für Adressfenster
        /// </remarks>
        [Column("NAME2")]
        public string? NAME2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Name des amtlichen Tierarztes in Kurzform".
        /// </summary>
        /// <remarks>
        /// Name (haupsächlich für #BSETESTZ Ergebnisfunktion)
        /// </remarks>
        [Column("NAME_TSLK")]
        public string? NAME_TSLK { get; set; }

        /// <summary>
        /// Gets or sets the value of "Name in Kurzform".
        /// </summary>
        /// <remarks>
        /// Name in Kurzform für Adressfenster
        /// </remarks>
        [Column("NAME")]
        public string? NAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nachname".
        /// </summary>
        /// <remarks>
        /// Nachname, inkl. Doppelnamen
        /// </remarks>
        [Column("NACHNAME")]
        public string? NACHNAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Systematischer Personenname".
        /// </summary>
        /// <remarks>
        /// vom System normierter Nachname und Vorname oder Name und Name2
        /// </remarks>
        [Column("SYS_NAME")]
        public string? SYS_NAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "storniert (Teil A)".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information im Teil A technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS_A")]
        public DateTime? SYS_BIS_A { get; set; }

        /// <summary>
        /// Gets or sets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Strasse Nr".
        /// </summary>
        /// <remarks>
        /// Straße und Hausnummer
        /// </remarks>
        [Column("STR_NR")]
        public string? STR_NR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Postanschrift abweichend".
        /// </summary>
        /// <remarks>
        /// Satz mit abweichender Postanschrft
        /// </remarks>
        [Column("POST_ABW")]
        public bool? POST_ABW { get; set; }

        /// <summary>
        /// Gets or sets the value of "Fax (1.Nummer) des zuständigen Tierarztes".
        /// </summary>
        /// <remarks>
        /// 1. Fax-Anschluß zur Benachrichtigung
        /// </remarks>
        [Column("TSLK_FAX1")]
        public string? TSLK_FAX1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Fax (2.Nummer) des zuständigen Tierarztes".
        /// </summary>
        /// <remarks>
        /// 2. Fax-Anschluß zur Benachrichtigung
        /// </remarks>
        [Column("TSLK_FAX2")]
        public string? TSLK_FAX2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Telefon (1.Nummer) des zuständigen Tierarztes".
        /// </summary>
        /// <remarks>
        /// 1. Telefonnummer zur Benachrichtigung
        /// </remarks>
        [Column("TSLK_FON1")]
        public string? TSLK_FON1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Telefon (1.Nummer) des zuständigen Tierarztes".
        /// </summary>
        /// <remarks>
        /// 2. Telefonnummer zur Benachrichtigung
        /// </remarks>
        [Column("TSLK_FON2")]
        public string? TSLK_FON2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "SMS (1.Nummer) des zuständigen Tierarztes".
        /// </summary>
        /// <remarks>
        /// 1. Handynummer für SMS zur Benachrichtigung
        /// </remarks>
        [Column("TSLK_SMS1")]
        public string? TSLK_SMS1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "SMS (1.Nummer) des zuständigen Tierarztes".
        /// </summary>
        /// <remarks>
        /// 2. Handynummer für SMS zur Benachrichtigung
        /// </remarks>
        [Column("TSLK_SMS2")]
        public string? TSLK_SMS2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorname".
        /// </summary>
        /// <remarks>
        /// ein oder mehrere Vornamen
        /// </remarks>
        [Column("VORNAME")]
        public string? VORNAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Verantwortlicher für die Datensendung Schlacht-Test-Kopplung".
        /// </summary>
        /// <remarks>
        /// i.d.R. zuständiger amtlicher Tierarzt
        /// </remarks>
        [Column("BNR15_TSLK")]
        public decimal? BNR15_TSLK { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anrede".
        /// </summary>
        /// <remarks>
        /// Anrede, ggf. mit Titel
        /// </remarks>
        [Column("ANREDE")]
        public string? ANREDE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        public decimal? BNR15 { get; set; }

    }
}
