// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// BSE-Test Proben-Identifikation Verwendungs-Zuteilung
    /// </summary>
    [Entity("BSETPIDZ")]
    public class BSETPIDZ
    {
        /// <summary>
        /// Gets or sets the value of "PID-Probe OG, Proben-Identifikation Zuordnungs-Obergrenze".
        /// </summary>
        /// <remarks>
        /// wird bei Prüfung als Obergrenze hinten ggf. mit x'FF' logisch ergänzt
        /// </remarks>
        [Column("BSEPID_S_O")]
        [Required]
        public string? BSEPID_S_O { get; set; }

        /// <summary>
        /// Gets or sets the value of "PID-Betrieb, Proben-Identifikation Ausgabebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Proben-ID-Bereich verwaltet (ursprünglich BSE, dann universell)
        /// </remarks>
        [Column("BSEPID_BNR")]
        [Required]
        public decimal? BSEPID_BNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Verantwortlicher für die Datensendung Schlacht-Test-Kopplung".
        /// </summary>
        /// <remarks>
        /// i.d.R. zuständiger amtlicher Tierarzt
        /// </remarks>
        [Column("BNR15_TSLK")]
        [Required]
        public decimal? BNR15_TSLK { get; set; }

        /// <summary>
        /// Gets or sets the value of "PID-Probe UG, Proben-Identifikation Zuordnungs-Untergrenze".
        /// </summary>
        /// <remarks>
        /// wird bei Prüfung als Untergrenze hinten abgeschnitten.
        /// </remarks>
        [Column("BSEPID_S_U")]
        [Required]
        public string? BSEPID_S_U { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "Satzstatus".
        /// </summary>
        /// <remarks>
        /// Systemstatus des Satzes
        /// </remarks>
        [Column("SYS_STAT")]
        public int? SYS_STAT { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

    }
}
