// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Data-Dictionary (ADIS) View CSETS inner join ELEMENTE
    /// </summary>
    [Entity("DA_DDI")]
    public class DA_DDI
    {
        /// <summary>
        /// Gets or sets the value of "Feldname".
        /// </summary>
        [Column("FELDNAME")]
        public string? FELDNAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Feldbez".
        /// </summary>
        [Column("FELDBEZ")]
        public string? FELDBEZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Definition".
        /// </summary>
        /// <remarks>
        /// ausführliche Definition des Feldes
        /// </remarks>
        [Column("DEFINITION")]
        public string? DEFINITION { get; set; }

        /// <summary>
        /// Gets or sets the value of "Data-Dictionary Spezifikation".
        /// </summary>
        /// <remarks>
        /// für ADIS ADED
        /// </remarks>
        [Column("DDSPEZ")]
        public string? DDSPEZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "DDI".
        /// </summary>
        [Column("DDI")]
        public string? DDI { get; set; }

        /// <summary>
        /// Gets or sets the value of "Auflösung, Anzhal Nachkommastellen (NK)".
        /// </summary>
        /// <remarks>
        /// für ADIS
        /// </remarks>
        [Column("AUFLOESUNG")]
        public int? AUFLOESUNG { get; set; }

        /// <summary>
        /// Gets or sets the value of "SetNr".
        /// </summary>
        [Column("SETNR")]
        public int? SETNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Minimum (analog MIN)".
        /// </summary>
        /// <remarks>
        /// für ADIS
        /// </remarks>
        [Column("MINIMUM")]
        public string? MINIMUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Maximum (analog MAX)".
        /// </summary>
        /// <remarks>
        /// für ADIS
        /// </remarks>
        [Column("MAXIMUM")]
        public string? MAXIMUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Laenge".
        /// </summary>
        [Column("LAENGE")]
        public int? LAENGE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kommentar".
        /// </summary>
        /// <remarks>
        /// für ADIS ADED
        /// </remarks>
        [Column("KOMMENTAR")]
        public string? KOMMENTAR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Format".
        /// </summary>
        [Column("FORMAT")]
        public string? FORMAT { get; set; }

    }
}
