// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Arzneimittelverwendung bei Fohlen, Equiden
    /// </summary>
    [Entity("EQ_FMED")]
    public class EQ_FMED
    {
        /// <summary>
        /// Gets or sets the value of "Registriernummer des Tierarztes/Transponder-Setzers".
        /// </summary>
        /// <remarks>
        /// Tierarzt oder sonstige sachkundige Person, die Transponder gesetzt hat, ggf. Organisation mit MBN
        /// </remarks>
        [Column("BNR15_CH_E")]
        [Required]
        public decimal? BNR15_CH_E { get; set; }

        /// <summary>
        /// Gets or sets the value of "Datum der Arzneimittelanwendung bei Fohlen, Equiden".
        /// </summary>
        [Column("MED_DAT_E")]
        [Required]
        public DateOnly? MED_DAT_E { get; set; }

        /// <summary>
        /// Gets or sets the value of "Transponder-Nr".
        /// </summary>
        /// <remarks>
        /// IDENTIFICATION NUMBER, momentan beschränkt auf Equiden
        /// </remarks>
        [Column("TRNR15")]
        [Required]
        public decimal? TRNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Registriernummer des Equidenhalters".
        /// </summary>
        [Column("BNR15_HE")]
        [Required]
        public decimal? BNR15_HE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Laufende Nummer der Arzneimittelverwendung am Tag".
        /// </summary>
        [Column("FMED_LFN")]
        [Required]
        public int? FMED_LFN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Eignung für den menschlichen Verzehr, nach Arzneimittelanwendung".
        /// </summary>
        [Column("LME_EX")]
        [Required]
        public int? LME_EX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Wartezeit in Tagen".
        /// </summary>
        /// <remarks>
        /// für Eignung für den menschlichen Verzehr, nach Arzneimittelanwendung
        /// </remarks>
        [Column("LME_WARTZ")]
        public int? LME_WARTZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Arzneimittel, angewendet bei Fohlen, Equiden".
        /// </summary>
        [Column("MED_ARZN")]
        [Required]
        public string? MED_ARZN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bemerkungen zur Arzneimittelanwendung bei Fohlen, Equiden".
        /// </summary>
        [Column("MED_BEM")]
        [Required]
        public string? MED_BEM { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldeweg".
        /// </summary>
        /// <remarks>
        /// Meldeweg (Post,IVR,IN...)
        /// </remarks>
        [Column("MELD_WG")]
        public int? MELD_WG { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "Satzstatus".
        /// </summary>
        /// <remarks>
        /// Systemstatus des Satzes
        /// </remarks>
        [Column("SYS_STAT")]
        public int? SYS_STAT { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

    }
}
