// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Attribute zum Bild für Foto-DB
    /// </summary>
    [Entity("FD_ATTR")]
    public class FD_ATTR
    {
        /// <summary>
        /// Gets or sets the value of "eindeutiger Key für Daten (in Form einer GUID)".
        /// </summary>
        /// <remarks>
        /// Format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (lower case)
        /// </remarks>
        [Column("FD_K_DATA")]
        [Required]
        public string? FD_K_DATA { get; set; }

        /// <summary>
        /// Gets or sets the value of "eindeutiger Key für Attribut (in Form einer GUID)".
        /// </summary>
        /// <remarks>
        /// Format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (lower case)
        /// </remarks>
        [Column("FD_K_ATTR")]
        [Required]
        public string? FD_K_ATTR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Attributwert (wahr).".
        /// </summary>
        [Column("FD_AT_BOOL")]
        public bool? FD_AT_BOOL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Eigenschaft wurde vorher geprüft".
        /// </summary>
        [Column("FD_AT_CHK")]
        public bool? FD_AT_CHK { get; set; }

        /// <summary>
        /// Gets or sets the value of "Attributwert (Datum).".
        /// </summary>
        [Column("FD_AT_DATE")]
        public DateOnly? FD_AT_DATE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Attributname".
        /// </summary>
        [Column("FD_AT_NAME")]
        [Required]
        public string? FD_AT_NAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Attributwert (numerisch)".
        /// </summary>
        [Column("FD_AT_NUM")]
        public decimal? FD_AT_NUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Attributwert (Text)".
        /// </summary>
        [Column("FD_AT_TEXT")]
        public string? FD_AT_TEXT { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

    }
}
