// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Funktionen mit Führungsentitäten und Parameter
    /// </summary>
    [Entity("FKT_PARM")]
    public class FKT_PARM
    {
        /// <summary>
        /// Gets or sets the value of "Funktion".
        /// </summary>
        /// <remarks>
        /// HIT-Abfragefunktionsname
        /// </remarks>
        [Column("FUNKTION")]
        [Required]
        public string? FUNKTION { get; set; }

        /// <summary>
        /// Gets or sets the value of "Entity".
        /// </summary>
        [Column("ENTITY")]
        [Required]
        public string? ENTITY { get; set; }

        /// <summary>
        /// Gets or sets the value of "Parameterliste".
        /// </summary>
        /// <remarks>
        /// Liste von Parametern für Funktionen
        /// </remarks>
        [Column("PARMLIST")]
        [Required]
        public string? PARMLIST { get; set; }

    }
}
