// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Bestandsregister (intern für BY-Durchschnitt)
    /// </summary>
    [Entity("FUNC_BESTREY")]
    public class FUNC_BESTREY
    {
        /// <summary>
        /// Gets or sets the value of "Geschlecht".
        /// </summary>
        /// <remarks>
        /// Geschlecht Rind
        /// </remarks>
        [Column("GESCHL_R")]
        public int? GESCHL_R { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nachbesitzer Betrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer des Nachbesitzers
        /// </remarks>
        [Column("BNR15_NB")]
        public decimal? BNR15_NB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorbesitzer Betrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer des Vorbesitzers
        /// </remarks>
        [Column("BNR15_VB")]
        public decimal? BNR15_VB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer Nachbesitzer (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Betriebsschlüssel für Ausgabe i.d.F. ll rkk gggg nnnn
        /// </remarks>
        [Column("BNR15_NBX")]
        public string? BNR15_NBX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Betriebsschlüssel für Ausgabe i.d.F. ll rkk gggg nnnn
        /// </remarks>
        [Column("BNR15_X")]
        public string? BNR15_X { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer Vorbesitzer (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Betriebsschlüssel für Ausgabe i.d.F. ll rkk gggg nnnn
        /// </remarks>
        [Column("BNR15_VBX")]
        public string? BNR15_VBX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Erstkalbedatum".
        /// </summary>
        /// <remarks>
        /// Datum der ersten Kalbung des Muttertieres
        /// </remarks>
        [Column("EKALBDAT")]
        public DateOnly? EKALBDAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geburtsdatum".
        /// </summary>
        /// <remarks>
        /// Geburtsdatum Rind
        /// </remarks>
        [Column("GEB_DATR")]
        public DateOnly? GEB_DATR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ohrmarke Erstkalb (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Ohrmarke des ersten Kalbes des Muttertieres (Alpha)
        /// </remarks>
        [Column("EKALBLOMX")]
        public string? EKALBLOMX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ohrmarke Erstkalb".
        /// </summary>
        /// <remarks>
        /// Ohrmarke des ersten Kalbes des Muttertieres
        /// </remarks>
        [Column("EKALBLOM")]
        public decimal? EKALBLOM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ausgangsdatum".
        /// </summary>
        /// <remarks>
        /// Ausgangsdatum für Bestandsregister u-ä.
        /// </remarks>
        [Column("DAT_AUS")]
        public DateOnly? DAT_AUS { get; set; }

        /// <summary>
        /// Gets or sets the value of "BIS-Datum".
        /// </summary>
        /// <remarks>
        /// Ober-Grenze für Abfragefunktionen
        /// </remarks>
        [Column("DAT_BIS")]
        public DateOnly? DAT_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Eingangsdatum".
        /// </summary>
        /// <remarks>
        /// Eingangsdatum für Bestandsregister u-ä.
        /// </remarks>
        [Column("DAT_EIN")]
        public DateOnly? DAT_EIN { get; set; }

        /// <summary>
        /// Gets or sets the value of "VON-Datum".
        /// </summary>
        /// <remarks>
        /// Unter-Grenze für Abfragefunktionen
        /// </remarks>
        [Column("DAT_VON")]
        public DateOnly? DAT_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geburtsbetrieb (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// , ggf. EU-Betrieb im Tierstamm
        /// </remarks>
        [Column("BNR15_GEX")]
        public string? BNR15_GEX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ende-Betrieb (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer des Endebetriebes im Tierende
        /// </remarks>
        [Column("BNR15_EBX")]
        public string? BNR15_EBX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anfangs-Betrieb (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer des Anfangsbetriebes
        /// </remarks>
        [Column("BNR15_ABX")]
        public string? BNR15_ABX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anfangs-Betrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer des Anfangsbetriebes, also Ersterfassung-, Geburt-, Markier- oder Einfuhrbetrieb
        /// </remarks>
        [Column("BNR15_AB")]
        public decimal? BNR15_AB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geburtsbetrieb".
        /// </summary>
        /// <remarks>
        /// Geburtsbetrieb bei Ersterfassungssatz
        /// </remarks>
        [Column("BNR15_GEB")]
        public decimal? BNR15_GEB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ende-Betrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer des Endebetriebes im Tierende
        /// </remarks>
        [Column("BNR15_EB")]
        public decimal? BNR15_EB { get; set; }

        /// <summary>
        /// Gets or sets the value of "gekalbt".
        /// </summary>
        /// <remarks>
        /// gekalbt, unabhängig von Alter und Geschlecht (z.B. falsche Kalbung)
        /// </remarks>
        [Column("BREGY_KA")]
        public decimal? BREGY_KA { get; set; }

        /// <summary>
        /// Gets or sets the value of "m0-3".
        /// </summary>
        /// <remarks>
        /// männlich 0-3 Monate
        /// </remarks>
        [Column("BREGY_M0")]
        public decimal? BREGY_M0 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m12-24".
        /// </summary>
        /// <remarks>
        /// männlich 12-24 Monate
        /// </remarks>
        [Column("BREGY_M12")]
        public decimal? BREGY_M12 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m12-18".
        /// </summary>
        /// <remarks>
        /// männlich 12-18 Monate
        /// </remarks>
        [Column("BREGY_M12A")]
        public decimal? BREGY_M12A { get; set; }

        /// <summary>
        /// Gets or sets the value of "m18-24".
        /// </summary>
        /// <remarks>
        /// männlich 18-24 Monate
        /// </remarks>
        [Column("BREGY_M18A")]
        public decimal? BREGY_M18A { get; set; }

        /// <summary>
        /// Gets or sets the value of "m24-30".
        /// </summary>
        /// <remarks>
        /// männlich 24-30 Monate
        /// </remarks>
        [Column("BREGY_M24")]
        public decimal? BREGY_M24 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m3-6".
        /// </summary>
        /// <remarks>
        /// männlich 3-6 Monate
        /// </remarks>
        [Column("BREGY_M3")]
        public decimal? BREGY_M3 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m>30".
        /// </summary>
        /// <remarks>
        /// männlich größer 30 Monate
        /// </remarks>
        [Column("BREGY_M30")]
        public decimal? BREGY_M30 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m6-9".
        /// </summary>
        /// <remarks>
        /// männlich 6-9 Monate
        /// </remarks>
        [Column("BREGY_M6")]
        public decimal? BREGY_M6 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m9-12".
        /// </summary>
        /// <remarks>
        /// männlich 9-12 Monate
        /// </remarks>
        [Column("BREGY_M9")]
        public decimal? BREGY_M9 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ohne".
        /// </summary>
        /// <remarks>
        /// Anzahl ohne Stammdaten
        /// </remarks>
        [Column("BREGY_OHN")]
        public decimal? BREGY_OHN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Summe".
        /// </summary>
        /// <remarks>
        /// Gesamtanzahl
        /// </remarks>
        [Column("BREGY_SUM")]
        public decimal? BREGY_SUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "w>30nk".
        /// </summary>
        /// <remarks>
        /// weiblich größer 30 Monate, nicht gekalbt
        /// </remarks>
        [Column("BREGY_W30N")]
        public decimal? BREGY_W30N { get; set; }

        /// <summary>
        /// Gets or sets the value of "w0-3".
        /// </summary>
        /// <remarks>
        /// weiblich 0-3 Monate
        /// </remarks>
        [Column("BREGY_W0")]
        public decimal? BREGY_W0 { get; set; }

        /// <summary>
        /// Gets or sets the value of "w12-24ka".
        /// </summary>
        /// <remarks>
        /// weiblich 12-24 Monate, gekalbt
        /// </remarks>
        [Column("BREGY_W12K")]
        public decimal? BREGY_W12K { get; set; }

        /// <summary>
        /// Gets or sets the value of "w>30ka".
        /// </summary>
        /// <remarks>
        /// weiblich größer 30 Monate, gekalbt
        /// </remarks>
        [Column("BREGY_W30K")]
        public decimal? BREGY_W30K { get; set; }

        /// <summary>
        /// Gets or sets the value of "w3-6".
        /// </summary>
        /// <remarks>
        /// weiblich 3-6 Monate
        /// </remarks>
        [Column("BREGY_W3")]
        public decimal? BREGY_W3 { get; set; }

        /// <summary>
        /// Gets or sets the value of "w12-24nk".
        /// </summary>
        /// <remarks>
        /// weiblich 12-24 Monate, nicht gekalbt
        /// </remarks>
        [Column("BREGY_W12N")]
        public decimal? BREGY_W12N { get; set; }

        /// <summary>
        /// Gets or sets the value of "w9-12".
        /// </summary>
        /// <remarks>
        /// weiblich 9-12 Monate
        /// </remarks>
        [Column("BREGY_W9")]
        public decimal? BREGY_W9 { get; set; }

        /// <summary>
        /// Gets or sets the value of "w12-24".
        /// </summary>
        /// <remarks>
        /// weiblich 12-24 Monate
        /// </remarks>
        [Column("BREGY_W12")]
        public decimal? BREGY_W12 { get; set; }

        /// <summary>
        /// Gets or sets the value of "w24-30nk".
        /// </summary>
        /// <remarks>
        /// weiblich 24-30 Monate, nicht gekalbt
        /// </remarks>
        [Column("BREGY_W24N")]
        public decimal? BREGY_W24N { get; set; }

        /// <summary>
        /// Gets or sets the value of "w6-9".
        /// </summary>
        /// <remarks>
        /// weiblich 6-9 Monate
        /// </remarks>
        [Column("BREGY_W6")]
        public decimal? BREGY_W6 { get; set; }

        /// <summary>
        /// Gets or sets the value of "w24-30ka".
        /// </summary>
        /// <remarks>
        /// weiblich 24-30 Monate, gekalbt
        /// </remarks>
        [Column("BREGY_W24K")]
        public decimal? BREGY_W24K { get; set; }

        /// <summary>
        /// Gets or sets the value of "Schlachtnummer".
        /// </summary>
        /// <remarks>
        /// Schlachtnr. des Schlachtbetriebes
        /// </remarks>
        [Column("SCHL_NR")]
        public decimal? SCHL_NR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tierendedatum".
        /// </summary>
        /// <remarks>
        /// Datum der Schlachtung, Verendung oder Ausfuhr
        /// </remarks>
        [Column("DAT_END")]
        public DateOnly? DAT_END { get; set; }

        /// <summary>
        /// Gets or sets the value of "w9-12ka".
        /// </summary>
        /// <remarks>
        /// weiblich 9-12 Monate, gekalbt
        /// </remarks>
        [Column("BREGY_W9K")]
        public decimal? BREGY_W9K { get; set; }

        /// <summary>
        /// Gets or sets the value of "w9-12nk".
        /// </summary>
        /// <remarks>
        /// weiblich 9-12 Monate, nicht gekalbt
        /// </remarks>
        [Column("BREGY_W9N")]
        public decimal? BREGY_W9N { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tier-Ende".
        /// </summary>
        /// <remarks>
        /// Tier-Ende Tod (differenziert!), Schlachtung ...
        /// </remarks>
        [Column("TIER_END")]
        public int? TIER_END { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tier-Ende (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Tier-Ende i.d.F XX
        /// </remarks>
        [Column("TIER_ENDX")]
        public string? TIER_ENDX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geschlecht Rind(aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Geschlecht Rind für Ausgabe i.d.F  M
        /// </remarks>
        [Column("GESCHL_X")]
        public string? GESCHL_X { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ursprungsstaat".
        /// </summary>
        /// <remarks>
        /// Staat aus dem das Tier direkt kommt
        /// </remarks>
        [Column("LAND_URS")]
        public int? LAND_URS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anzahl Kalbungen".
        /// </summary>
        /// <remarks>
        /// Anzahl Kalbungen des Muttertieres (Zwillinge sind eine Kalbung)
        /// </remarks>
        [Column("KALBUNGANZ")]
        public int? KALBUNGANZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "GVE".
        /// </summary>
        /// <remarks>
        /// durchschnittliche GVE im Zeitraum
        /// </remarks>
        [Column("GVE")]
        public decimal? GVE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Schlachtgewicht".
        /// </summary>
        /// <remarks>
        /// Gewicht des Schlachtkörpers
        /// </remarks>
        [Column("SCHL_GEW")]
        public decimal? SCHL_GEW { get; set; }

        /// <summary>
        /// Gets or sets the value of "GVE letztes 8tel Vorjahr".
        /// </summary>
        /// <remarks>
        /// durchschnittliche GVE 15.10-31.12 des Vorjahres zum Vergleich für GVE Korrektur
        /// </remarks>
        [Column("GVE_L8VJA")]
        public decimal? GVE_L8VJA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tier-Ausgang".
        /// </summary>
        /// <remarks>
        /// Ausgangsmeldung (analog TIER_END + Abgang)
        /// </remarks>
        [Column("TIER_AUS")]
        public int? TIER_AUS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tier-Ausgang (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Tier-Ausgang i.d.F XX
        /// </remarks>
        [Column("TIER_AUSX")]
        public string? TIER_AUSX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anzahl Kälber".
        /// </summary>
        /// <remarks>
        /// Anzahl Kälber des Muttertieres
        /// </remarks>
        [Column("KALBANZ")]
        public int? KALBANZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Letztkalbedatum".
        /// </summary>
        /// <remarks>
        /// Datum der letzten, also jüngsten Kalbung des Muttertieres
        /// </remarks>
        [Column("LKALBDAT")]
        public DateOnly? LKALBDAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "GVE letztes 8tel heuer".
        /// </summary>
        /// <remarks>
        /// durchschnittliche GVE 15.10-31.12 des Vorjahres für GVE Korrektur um 0.8
        /// </remarks>
        [Column("GVE_L8HEU")]
        public decimal? GVE_L8HEU { get; set; }

        /// <summary>
        /// Gets or sets the value of "Rasse (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Rasse für Ausgabe i.d.F  1,RBT
        /// </remarks>
        [Column("RASSE_X")]
        public string? RASSE_X { get; set; }

        /// <summary>
        /// Gets or sets the value of "Rasse".
        /// </summary>
        /// <remarks>
        /// Rasse laut ADR-Schlüssel
        /// </remarks>
        [Column("RASSE")]
        public int? RASSE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ohrmarke Tier (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// nur in Funktionen, wenn der Benutzer keine Möglichkeit hat ALPHALOM selber aufzurufen)
        /// </remarks>
        [Column("LOM_X")]
        public string? LOM_X { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ohrmarke Mutter".
        /// </summary>
        /// <remarks>
        /// Ohrmarke Muttertier aufbereitet (DE..) oder alte alphanumerische Marke
        /// </remarks>
        [Column("LOM_MUTX")]
        public string? LOM_MUTX { get; set; }

        /// <summary>
        /// Gets or sets the value of "alte Alfa-Ohrmarke".
        /// </summary>
        [Column("LOM_A")]
        public string? LOM_A { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ohrmarke".
        /// </summary>
        /// <remarks>
        /// IDENTIFICATION NUMBER
        /// </remarks>
        [Column("LOM")]
        public decimal? LOM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ursprungsstaat (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Staat für Ausgabe i.d.F 040,Österreich
        /// </remarks>
        [Column("LAND_URX")]
        public string? LAND_URX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Mutter".
        /// </summary>
        /// <remarks>
        /// Ohrmarkennummer Muttertier
        /// </remarks>
        [Column("LOM_MUT")]
        public decimal? LOM_MUT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tier-Eingang (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Tier-Eingang i.d.F XX
        /// </remarks>
        [Column("TIER_EINX")]
        public string? TIER_EINX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kategorie".
        /// </summary>
        /// <remarks>
        /// Kategorie des Schlachtkörpers
        /// </remarks>
        [Column("SCHL_KAT")]
        public int? SCHL_KAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Lebendgewicht".
        /// </summary>
        /// <remarks>
        /// Lebendgewicht vor Schlachtung
        /// </remarks>
        [Column("SCHL_LEB")]
        public decimal? SCHL_LEB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kategorie (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Kategorie  i.d.F XX
        /// </remarks>
        [Column("SCHL_KATX")]
        public string? SCHL_KATX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tier-Eingang".
        /// </summary>
        /// <remarks>
        /// Tier-Eingang durch Geburt, Impmark, Zugang ... (analog TIER_ANF + Zugang)
        /// </remarks>
        [Column("TIER_EIN")]
        public int? TIER_EIN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Letzten 5 Ziffern der Ohrmarke".
        /// </summary>
        [Column("LOM5")]
        public string? LOM5 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Rind am Betrieb geboren".
        /// </summary>
        [Column("GEB_EIGEN")]
        public bool? GEB_EIGEN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Rind weiblich ab 8 Monate (TAM)".
        /// </summary>
        [Column("BREG_TAMRW")]
        public decimal? BREG_TAMRW { get; set; }

        /// <summary>
        /// Gets or sets the value of "Alter (in Monaten und Tagen)".
        /// </summary>
        /// <remarks>
        /// Alter bei Abgang oder Zeitraumende
        /// </remarks>
        [Column("ALTER")]
        public decimal? ALTER { get; set; }

        /// <summary>
        /// Gets or sets the value of "Alter (als Text in Monaten und Tagen)".
        /// </summary>
        /// <remarks>
        /// Alter bei Abgang oder Zeitraumende i.d.F. x Mon. x Tg.
        /// </remarks>
        [Column("ALTERA")]
        public string? ALTERA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Alter (in Monaten und Bruchteile von Monaten)".
        /// </summary>
        /// <remarks>
        /// Alter bei Abgang oder Zeitraumende mit Nachkommastellen (ein Tag sind 0.0322580645 Monate)
        /// </remarks>
        [Column("ALTERX")]
        public decimal? ALTERX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer des Betriebsteils".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15_BT")]
        public decimal? BNR15_BT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer des Betriebsteils (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Betriebsschlüssel für Ausgabe i.d.F. ll rkk gggg nnnn
        /// </remarks>
        [Column("BNR15_BT_X")]
        public string? BNR15_BT_X { get; set; }

        /// <summary>
        /// Gets or sets the value of "Altrind männlich ab 27 Monate (Düngegesetz)".
        /// </summary>
        [Column("BREG_DG_AM")]
        public decimal? BREG_DG_AM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Altrind weiblich ab 27 Monate (Düngegesetz)".
        /// </summary>
        [Column("BREG_DG_AW")]
        public decimal? BREG_DG_AW { get; set; }

        /// <summary>
        /// Gets or sets the value of "Jungrind männlich ab 4 - 27 Monate (Düngegesetz)".
        /// </summary>
        [Column("BREG_DG_JM")]
        public decimal? BREG_DG_JM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Jungrind weiblich ab 4 - 27 Monate (Düngegesetz)".
        /// </summary>
        [Column("BREG_DG_JW")]
        public decimal? BREG_DG_JW { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kalb männlich 0-4 Monate (Düngegesetz)".
        /// </summary>
        [Column("BREG_DG_KM")]
        public decimal? BREG_DG_KM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kalb weiblich 0-4 Monate (Düngegesetz)".
        /// </summary>
        [Column("BREG_DG_KW")]
        public decimal? BREG_DG_KW { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kalb männlich 0-8 Monate (TAM)".
        /// </summary>
        [Column("BREG_TAMKM")]
        public decimal? BREG_TAMKM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kalb weiblich 0-8 Monate (TAM)".
        /// </summary>
        [Column("BREG_TAMKW")]
        public decimal? BREG_TAMKW { get; set; }

        /// <summary>
        /// Gets or sets the value of "Rind männlich ab 8 Monate (TAM)".
        /// </summary>
        [Column("BREG_TAMRM")]
        public decimal? BREG_TAMRM { get; set; }

        /// <summary>
        /// Gets or sets the value of "m0-4".
        /// </summary>
        /// <remarks>
        /// männlich 0-4 Monate
        /// </remarks>
        [Column("BRYDG_M0")]
        public decimal? BRYDG_M0 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m12-24".
        /// </summary>
        /// <remarks>
        /// männlich 12-24 Monate
        /// </remarks>
        [Column("BRYDG_M12")]
        public decimal? BRYDG_M12 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m24-27".
        /// </summary>
        /// <remarks>
        /// männlich 24-27 Monate
        /// </remarks>
        [Column("BRYDG_M24")]
        public decimal? BRYDG_M24 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m>27".
        /// </summary>
        /// <remarks>
        /// männlich größer 27 Monate
        /// </remarks>
        [Column("BRYDG_M27")]
        public decimal? BRYDG_M27 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m4-6".
        /// </summary>
        /// <remarks>
        /// männlich 4-6 Monate
        /// </remarks>
        [Column("BRYDG_M4")]
        public decimal? BRYDG_M4 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m6-9".
        /// </summary>
        /// <remarks>
        /// männlich 6-9 Monate
        /// </remarks>
        [Column("BRYDG_M6")]
        public decimal? BRYDG_M6 { get; set; }

        /// <summary>
        /// Gets or sets the value of "m9-12".
        /// </summary>
        /// <remarks>
        /// männlich 9-12 Monate
        /// </remarks>
        [Column("BRYDG_M9")]
        public decimal? BRYDG_M9 { get; set; }

        /// <summary>
        /// Gets or sets the value of "w0-4".
        /// </summary>
        /// <remarks>
        /// weiblich 0-4 Monate
        /// </remarks>
        [Column("BRYDG_W0")]
        public decimal? BRYDG_W0 { get; set; }

        /// <summary>
        /// Gets or sets the value of "w12-24ka".
        /// </summary>
        /// <remarks>
        /// weiblich 12-24 Monate, gekalbt
        /// </remarks>
        [Column("BRYDG_W12K")]
        public decimal? BRYDG_W12K { get; set; }

        /// <summary>
        /// Gets or sets the value of "w12-24nk".
        /// </summary>
        /// <remarks>
        /// weiblich 12-24 Monate, nicht gekalbt
        /// </remarks>
        [Column("BRYDG_W12N")]
        public decimal? BRYDG_W12N { get; set; }

        /// <summary>
        /// Gets or sets the value of "w24-27ka".
        /// </summary>
        /// <remarks>
        /// weiblich 24-27 Monate, gekalbt
        /// </remarks>
        [Column("BRYDG_W24K")]
        public decimal? BRYDG_W24K { get; set; }

        /// <summary>
        /// Gets or sets the value of "w24-27nk".
        /// </summary>
        /// <remarks>
        /// weiblich 24-27 Monate, nicht gekalbt
        /// </remarks>
        [Column("BRYDG_W24N")]
        public decimal? BRYDG_W24N { get; set; }

        /// <summary>
        /// Gets or sets the value of "w>27ka".
        /// </summary>
        /// <remarks>
        /// weiblich größer 27 Monate, gekalbt
        /// </remarks>
        [Column("BRYDG_W27K")]
        public decimal? BRYDG_W27K { get; set; }

        /// <summary>
        /// Gets or sets the value of "w>27nk".
        /// </summary>
        /// <remarks>
        /// weiblich größer 27 Monate, nicht gekalbt
        /// </remarks>
        [Column("BRYDG_W27N")]
        public decimal? BRYDG_W27N { get; set; }

        /// <summary>
        /// Gets or sets the value of "w4-6".
        /// </summary>
        /// <remarks>
        /// weiblich 4-6 Monate
        /// </remarks>
        [Column("BRYDG_W4")]
        public decimal? BRYDG_W4 { get; set; }

        /// <summary>
        /// Gets or sets the value of "w6-9".
        /// </summary>
        /// <remarks>
        /// weiblich 6-9 Monate
        /// </remarks>
        [Column("BRYDG_W6")]
        public decimal? BRYDG_W6 { get; set; }

        /// <summary>
        /// Gets or sets the value of "w9-12".
        /// </summary>
        /// <remarks>
        /// weiblich 9-12 Monate
        /// </remarks>
        [Column("BRYDG_W9")]
        public decimal? BRYDG_W9 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anfangsdatum des Tieres".
        /// </summary>
        /// <remarks>
        /// Anfangsdatum im Tierstamm
        /// </remarks>
        [Column("DAT_ANF")]
        public DateOnly? DAT_ANF { get; set; }

        /// <summary>
        /// Gets or sets the value of "Möglicher Fehler bei GVE".
        /// </summary>
        /// <remarks>
        /// sehr zeitaufwändig, daher nur wenn Parameter GVE_ERR_MO gesetzt
        /// </remarks>
        [Column("GVE_ERROR")]
        public int? GVE_ERROR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Individuelle Bemerkung".
        /// </summary>
        [Column("RD_BEMERK")]
        public string? RD_BEMERK { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer des Betriebes bzw. der Betriebsstätte, unter der Rinddaten gespeichert sind".
        /// </summary>
        [Column("RD_BNR15")]
        public decimal? RD_BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer des Betriebes bzw. des Unternehmens, unter der Rinddaten gespeichert sind".
        /// </summary>
        [Column("RD_BNR15UN")]
        public decimal? RD_BNR15UN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Individuelle Angabe eines Datums, für betriebliche Verwendung".
        /// </summary>
        [Column("RD_DATUM")]
        public DateOnly? RD_DATUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Individuelle Nutzungsangabe".
        /// </summary>
        [Column("RD_INUTZ")]
        public int? RD_INUTZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Stallnummer oder alternativ Tiername".
        /// </summary>
        [Column("RD_STALLNR")]
        public string? RD_STALLNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bezeichnung für Betriebsteil, Herde oder Gruppe".
        /// </summary>
        [Column("RD_TEILBEZ")]
        public string? RD_TEILBEZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nummer für Betriebsteil, Herde oder Gruppe".
        /// </summary>
        [Column("RD_TEILNR")]
        public int? RD_TEILNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Individuelle Angabe einer Dezimalzahl, für betriebliche Verwendung".
        /// </summary>
        [Column("RD_WERTD")]
        public decimal? RD_WERTD { get; set; }

        /// <summary>
        /// Gets or sets the value of "Individuelle Angabe einer Ganzzahl, für betriebliche Verwendung".
        /// </summary>
        [Column("RD_WERTG")]
        public Int64? RD_WERTG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tier-Anfang".
        /// </summary>
        /// <remarks>
        /// Tier-Anfang durch Geburt, Impmark ...
        /// </remarks>
        [Column("TIER_ANF")]
        public int? TIER_ANF { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tier-Anfang (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Tier-Anfang  i.d.F XX
        /// </remarks>
        [Column("TIER_ANFX")]
        public string? TIER_ANFX { get; set; }

        /// <summary>
        /// Gets or sets the value of "durchschnittliche Zwischenkalbezeit (in Monaten und Bruchteile von Monaten)".
        /// </summary>
        /// <remarks>
        /// Abstand letzter zu ersten Kalbung geteilt durch Anzahl, in Monaten (ein Tag sind 0.0322580645 Mon.)
        /// </remarks>
        [Column("ZKZ_DURCH")]
        public decimal? ZKZ_DURCH { get; set; }

        /// <summary>
        /// Gets or sets the value of "durchschnittliche Zwischenkalbezeit (in Tagen)".
        /// </summary>
        /// <remarks>
        /// Abstand letzter zu ersten Kalbung geteilt durch Anzahl, in Tagen
        /// </remarks>
        [Column("ZKZ_DURCHT")]
        public Int64? ZKZ_DURCHT { get; set; }

    }
}
