// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Freie Passnummern in zugeteilten Heimtierausweisserien
    /// </summary>
    [Entity("FUNC_HTPFREE")]
    public class FUNC_HTPFREE
    {
        /// <summary>
        /// Gets or sets the value of "Status der Heimtierausweisserien (offen, ausgegeben, usw.)".
        /// </summary>
        [Column("HTPFREE_S")]
        public int? HTPFREE_S { get; set; }

        /// <summary>
        /// Gets or sets the value of "Obergrenze der Heimtierausweis Nummernserie (aufbereitet)".
        /// </summary>
        [Column("HT_PASSOGX")]
        public string? HT_PASSOGX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Untergrenze der Heimtierausweis Nummernserie (aufbereitet)".
        /// </summary>
        [Column("HT_PASSUGX")]
        public string? HT_PASSUGX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anzahl Heimtierpässe, im Intervall".
        /// </summary>
        [Column("HTPFREEANZ")]
        public Int64? HTPFREEANZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer ermächtigter Tierarzt, für Ausgaben von Heimtierpässen".
        /// </summary>
        [Column("BNR15_HTA")]
        public decimal? BNR15_HTA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer ermächtigter Tierarzt für Heimtierpässe (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Betriebsschlüssel für Ausgabe i.d.F. ll rkk gggg nnnn
        /// </remarks>
        [Column("BNR15_HTAX")]
        public string? BNR15_HTAX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer Druck legende Stelle für Heimtierpässe".
        /// </summary>
        [Column("BNR15_HTD")]
        public decimal? BNR15_HTD { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer Druck legende Stelle für Heimtierpässe (aufbereitet)".
        /// </summary>
        /// <remarks>
        /// Betriebsschlüssel für Ausgabe i.d.F. ll rkk gggg nnnn
        /// </remarks>
        [Column("BNR15_HTDX")]
        public string? BNR15_HTDX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Obergrenze der Heimtierausweis Nummernserie".
        /// </summary>
        [Column("HT_PASSOG")]
        public decimal? HT_PASSOG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Untergrenze der Heimtierausweis Nummernserie".
        /// </summary>
        [Column("HT_PASSUG")]
        public decimal? HT_PASSUG { get; set; }

    }
}
