// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Ausfuhrmeldung aus Mitgliedsstaat zum Austausch
    /// </summary>
    [Entity("MSA_AUSF")]
    public class MSA_AUSF
    {
        /// <summary>
        /// Gets or sets the value of "Zielstaat".
        /// </summary>
        /// <remarks>
        /// Bestimmungsstaat bei Ausfuhr
        /// </remarks>
        [Column("LAND_ZIE")]
        [Required]
        public int? LAND_ZIE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ohrmarke".
        /// </summary>
        /// <remarks>
        /// IDENTIFICATION NUMBER
        /// </remarks>
        [Column("LOM")]
        [Required]
        public decimal? LOM { get; set; }

        /// <summary>
        /// Gets or sets the value of "alte Alfa-Ohrmarke".
        /// </summary>
        [Column("LOM_A")]
        public string? LOM_A { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ausfuhrdatum".
        /// </summary>
        [Column("AUSF_DAT")]
        [Required]
        public DateOnly? AUSF_DAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anfangs-Betrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer des Anfangsbetriebes, also Ersterfassung-, Geburt-, Markier- oder Einfuhrbetrieb
        /// </remarks>
        [Column("BNR15_AB")]
        public decimal? BNR15_AB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geburtsdatum".
        /// </summary>
        /// <remarks>
        /// Geburtsdatum Rind
        /// </remarks>
        [Column("GEB_DATR")]
        public DateOnly? GEB_DATR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geschlecht".
        /// </summary>
        /// <remarks>
        /// Geschlecht Rind
        /// </remarks>
        [Column("GESCHL_R")]
        public int? GESCHL_R { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kalbungsstatus".
        /// </summary>
        /// <remarks>
        /// ist eine Kalbung (über Geburtsmeldung) bekannt
        /// </remarks>
        [Column("KALBSTAT")]
        public int? KALBSTAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geburtsstaat".
        /// </summary>
        /// <remarks>
        /// Geburtsstaat
        /// </remarks>
        [Column("LAND_GEB")]
        public int? LAND_GEB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Mitgliedsstaat Austauschquelle".
        /// </summary>
        /// <remarks>
        /// Mitgliedsstaat für Datenaustausch der die Daten bereit gestellt hat
        /// </remarks>
        [Column("LAND_MSA")]
        [Required]
        public int? LAND_MSA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ursprungsstaat".
        /// </summary>
        /// <remarks>
        /// Staat aus dem das Tier direkt kommt
        /// </remarks>
        [Column("LAND_URS")]
        public int? LAND_URS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Mutter".
        /// </summary>
        /// <remarks>
        /// Ohrmarkennummer Muttertier
        /// </remarks>
        [Column("LOM_MUT")]
        public decimal? LOM_MUT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ohrmarke Vater".
        /// </summary>
        /// <remarks>
        /// Ohrmarkennummer Vatertier
        /// </remarks>
        [Column("LOM_VAT")]
        public decimal? LOM_VAT { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        [Required]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldeweg".
        /// </summary>
        /// <remarks>
        /// Meldeweg (Post,IVR,IN...)
        /// </remarks>
        [Column("MELD_WG")]
        public int? MELD_WG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Prämienstatus für EU-Datenaustausch zwischen MS".
        /// </summary>
        /// <remarks>
        /// Prämienstatus bei Bestandsprämie im Mitgliedsstaat oder aus EU-Einfuhr
        /// </remarks>
        [Column("MSA_PRAEM")]
        public int? MSA_PRAEM { get; set; }

        /// <summary>
        /// Gets or sets the value of "EU-Rasseschlüssel".
        /// </summary>
        /// <remarks>
        /// Einheitlicher EU-Rasseschlüssel für Datenaustausch
        /// </remarks>
        [Column("MSA_RASSE")]
        public Int64? MSA_RASSE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Veterinärsperre im MS für EU-Datenaustausch".
        /// </summary>
        /// <remarks>
        /// Veterinärsperre im MS laut gemeinsamer Schlüsselliste
        /// </remarks>
        [Column("MSA_SPERRE")]
        public int? MSA_SPERRE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Rasse des Ursprungsstaates".
        /// </summary>
        /// <remarks>
        /// Rasse normiert laut Schlüssel des Daten-Lieferanten
        /// </remarks>
        [Column("RASSE_URS")]
        public int? RASSE_URS { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "Cluster-Spalte".
        /// </summary>
        /// <remarks>
        /// Systemintern
        /// </remarks>
        [Column("SYS_CLUST")]
        public int? SYS_CLUST { get; set; }

        /// <summary>
        /// Gets the value of "Satzstatus".
        /// </summary>
        /// <remarks>
        /// Systemstatus des Satzes
        /// </remarks>
        [Column("SYS_STAT")]
        public int? SYS_STAT { get; set; }

    }
}
