// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// OIDC Client-Redirects
    /// </summary>
    [Entity("OAREDIR")]
    public class OAREDIR
    {
        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets or sets the value of "OIDC-Client-Id".
        /// </summary>
        /// <remarks>
        /// (case sensitive, Kunde und HIT/ZID vereinbaren, Buchstaben + Ziffern)
        /// </remarks>
        [Column("OI_C_ID")]
        [Required]
        public string? OI_C_ID { get; set; }

        /// <summary>
        /// Gets or sets the value of "OIDC-URI gültig bis".
        /// </summary>
        /// <remarks>
        /// exkludiert
        /// </remarks>
        [Column("OI_RED_BIS")]
        [Required]
        public DateTime? OI_RED_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Weiterleitungs-URI für OAuth-Antworten".
        /// </summary>
        [Column("OI_RED_URI")]
        [Required]
        public string? OI_RED_URI { get; set; }

        /// <summary>
        /// Gets or sets the value of "OIDC-URI gültig ab".
        /// </summary>
        /// <remarks>
        /// inkludiert
        /// </remarks>
        [Column("OI_RED_VON")]
        [Required]
        public DateTime? OI_RED_VON { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Redirect-URI-Typ".
        /// </summary>
        [Column("OA_RED_TYP")]
        [Required]
        public int? OA_RED_TYP { get; set; }

    }
}
