// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Antrag nach Milchsteigerungsvermeidungsbeihilfenverordnung (MiBe2)
    /// </summary>
    [Entity("PRMMREDM2")]
    public class PRMMREDM2
    {
        /// <summary>
        /// Gets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer des Antragstellers".
        /// </summary>
        [Column("BNR15_AS")]
        [Required]
        public decimal? BNR15_AS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer Tierhalter".
        /// </summary>
        /// <remarks>
        /// speziell im Bereich Tierarzneimittel (TAM)
        /// </remarks>
        [Column("BNR15_HA")]
        [Required]
        public decimal? BNR15_HA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorgangsnummer".
        /// </summary>
        [Column("MRED2_ANR")]
        [Required]
        public Int64? MRED2_ANR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nachweise zu gelieferten Mengen".
        /// </summary>
        [Column("MRED2_B1")]
        [Required]
        public bool? MRED2_B1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Verpflichtung zur Unterlassung der Steigerung".
        /// </summary>
        [Column("MRED2_B2")]
        [Required]
        public bool? MRED2_B2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Erklärung der Nichtüberlassung".
        /// </summary>
        [Column("MRED2_B3")]
        [Required]
        public bool? MRED2_B3 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Einverständniserklärung".
        /// </summary>
        [Column("MRED2_B4")]
        [Required]
        public bool? MRED2_B4 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Beihilfefähige Menge (in kg)".
        /// </summary>
        [Column("MRED2_BEME")]
        [Required]
        public decimal? MRED2_BEME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsinhaber-Wechsel".
        /// </summary>
        [Column("MRED2_BIWE")]
        [Required]
        public bool? MRED2_BIWE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Menge Bezugszeitraum (in kg)".
        /// </summary>
        [Column("MRED2_MEBZ")]
        [Required]
        public decimal? MRED2_MEBZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorschuss beantragt".
        /// </summary>
        [Column("MRED2_VOBE")]
        [Required]
        public bool? MRED2_VOBE { get; set; }

        /// <summary>
        /// Gets or sets the value of "BIS der Bankverbindung".
        /// </summary>
        [Column("MRED_BIC")]
        [Required]
        public string? MRED_BIC { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kontoinhaber zur Bankverbindung".
        /// </summary>
        [Column("MRED_BNAME")]
        [Required]
        public string? MRED_BNAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "IBAN der Bankverbindung".
        /// </summary>
        [Column("MRED_IBAN")]
        [Required]
        public string? MRED_IBAN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Globally Unique Identifier".
        /// </summary>
        /// <remarks>
        /// Format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (lower case)
        /// </remarks>
        [Column("GUID")]
        public string? GUID { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldeweg".
        /// </summary>
        /// <remarks>
        /// Meldeweg (Post,IVR,IN...)
        /// </remarks>
        [Column("MELD_WG")]
        public int? MELD_WG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Verpflichtung Kuhmilcherzeuger".
        /// </summary>
        [Column("MRED2_B5")]
        [Required]
        public bool? MRED2_B5 { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "Satzstatus".
        /// </summary>
        /// <remarks>
        /// Systemstatus des Satzes
        /// </remarks>
        [Column("SYS_STAT")]
        public int? SYS_STAT { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

    }
}
