// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Milch Reduktion Zahlungsantrag + Verwaltungskontrolle  (View, nur aktuelle)
    /// </summary>
    [Entity("PRMMREDZV")]
    public class PRMMREDZV
    {
        /// <summary>
        /// Gets or sets the value of "Betriebsnummer des Antragstellers".
        /// </summary>
        [Column("BNR15_AS")]
        [Required]
        public decimal? BNR15_AS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer Tierhalter".
        /// </summary>
        /// <remarks>
        /// speziell im Bereich Tierarzneimittel (TAM)
        /// </remarks>
        [Column("BNR15_HA")]
        [Required]
        public decimal? BNR15_HA { get; set; }

        /// <summary>
        /// Gets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bestätigung war Milchlieferer im geforderten Monat".
        /// </summary>
        /// <remarks>
        /// für Runde 1 ist das Juli 2016
        /// </remarks>
        [Column("MRED_B1")]
        public bool? MRED_B1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bestätigung Erklärungen gelesen und akzeptiert".
        /// </summary>
        [Column("MRED_B2")]
        public bool? MRED_B2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "BIS der Bankverbindung".
        /// </summary>
        [Column("MRED_BIC")]
        [Required]
        public string? MRED_BIC { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kontoinhaber zur Bankverbindung".
        /// </summary>
        [Column("MRED_BNAME")]
        [Required]
        public string? MRED_BNAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Radio - Konto angegeben (ja) oder wie in Zahlstelle (nein)".
        /// </summary>
        [Column("MRED_BVA")]
        [Required]
        public bool? MRED_BVA { get; set; }

        /// <summary>
        /// Gets or sets the value of "IBAN der Bankverbindung".
        /// </summary>
        [Column("MRED_IBAN")]
        [Required]
        public string? MRED_IBAN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Daten plausibel".
        /// </summary>
        [Column("MRED_OK")]
        [Required]
        public bool? MRED_OK { get; set; }

        /// <summary>
        /// Gets or sets the value of "Milchreduktionsverfahren, Runde".
        /// </summary>
        [Column("MRED_RND")]
        [Required]
        public int? MRED_RND { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tatsächlich gelieferte Menge im 1. Monat des Zielzeitraum".
        /// </summary>
        /// <remarks>
        /// für Runde 1 ist das Okt. 2016
        /// </remarks>
        [Column("MRED_T1")]
        public decimal? MRED_T1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tatsächlich gelieferte Menge im 2. Monat des Zielzeitraum".
        /// </summary>
        /// <remarks>
        /// für Runde 1 ist das Nov. 2016
        /// </remarks>
        [Column("MRED_T2")]
        public decimal? MRED_T2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tatsächlich gelieferte Menge im 3. Monat des Zielzeitraum".
        /// </summary>
        /// <remarks>
        /// für Runde 1 ist das Dez. 2016
        /// </remarks>
        [Column("MRED_T3")]
        public decimal? MRED_T3 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tatsächliche Reduktion im Zielzeitraum".
        /// </summary>
        /// <remarks>
        /// für Runde 1 ist das Okt. - Dez. 2016
        /// </remarks>
        [Column("MRED_TRED")]
        public decimal? MRED_TRED { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tatsächlich gelieferte Menge im Zielzeitraum".
        /// </summary>
        /// <remarks>
        /// für Runde 1 ist das Okt. - Dez. 2016
        /// </remarks>
        [Column("MRED_TSUM")]
        public decimal? MRED_TSUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Abzugsbetrag (Diffferenz Bruttobetrag zu Auszahlungsbetrag)".
        /// </summary>
        [Column("MRED_ABZBE")]
        public decimal? MRED_ABZBE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Auszahlungsbetrag (nach Kürzung mit Auszahlungsfaktor)".
        /// </summary>
        [Column("MRED_AUSBE")]
        public decimal? MRED_AUSBE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Auszahlungsklasse".
        /// </summary>
        [Column("MRED_AUSKL")]
        public int? MRED_AUSKL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Beantragte Reduktionsmenge".
        /// </summary>
        [Column("MRED_BRED")]
        public decimal? MRED_BRED { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bruttobetrag (ohne Kürzung mit Auszahlungsfaktor)".
        /// </summary>
        [Column("MRED_BRUBE")]
        public decimal? MRED_BRUBE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Genehmigte Reduktionsmenge gemäß Bescheid".
        /// </summary>
        [Column("MRED_GRED")]
        public decimal? MRED_GRED { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geplante Reduktion".
        /// </summary>
        /// <remarks>
        /// errechnet sich aus MSUM - MZIEL
        /// </remarks>
        [Column("MRED_MRED")]
        public decimal? MRED_MRED { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gelieferte Menge, Summe über gesamten Referenzzeitraum".
        /// </summary>
        /// <remarks>
        /// für Runde 1 ist das Okt. - Dez. 2015
        /// </remarks>
        [Column("MRED_MSUM")]
        public decimal? MRED_MSUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gelieferte Menge im 1. Monat des Referenzzeitraums, laut VWK".
        /// </summary>
        [Column("MRED_V1")]
        public decimal? MRED_V1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gelieferte Menge im 2. Monat des Referenzzeitraums, laut VWK".
        /// </summary>
        [Column("MRED_V2")]
        public decimal? MRED_V2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gelieferte Menge im 3. Monat des Referenzzeitraums, laut VWK".
        /// </summary>
        [Column("MRED_V3")]
        public decimal? MRED_V3 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Datum der Ankündigung der VOK".
        /// </summary>
        [Column("MRED_VADAT")]
        public DateOnly? MRED_VADAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "VOK Beschreibung der Beanstandungen".
        /// </summary>
        [Column("MRED_VBEA")]
        [Required]
        public string? MRED_VBEA { get; set; }

        /// <summary>
        /// Gets or sets the value of "VOK Kommentar zu Subventionsbetrug".
        /// </summary>
        [Column("MRED_VBETR")]
        [Required]
        public string? MRED_VBETR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Datum der gestatteten VOK".
        /// </summary>
        [Column("MRED_VGDAT")]
        public DateOnly? MRED_VGDAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "VOK angekündigt".
        /// </summary>
        [Column("MRED_VOK1")]
        public bool? MRED_VOK1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "VOK gestattet".
        /// </summary>
        [Column("MRED_VOK2")]
        public bool? MRED_VOK2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "VOK ergab Beanstandungen".
        /// </summary>
        [Column("MRED_VOK3")]
        public bool? MRED_VOK3 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Hinweise auf vorsätzlich falsche Angaben".
        /// </summary>
        [Column("MRED_VOK4")]
        public bool? MRED_VOK4 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Hinweise auf einen Subventionsbetrug".
        /// </summary>
        [Column("MRED_VOK5")]
        public bool? MRED_VOK5 { get; set; }

        /// <summary>
        /// Gets or sets the value of "VOK Wertung, bezüglich Auszahlung".
        /// </summary>
        [Column("MRED_VOKWE")]
        public int? MRED_VOKWE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geplante Reduktion, laut VWK".
        /// </summary>
        [Column("MRED_VRED")]
        public decimal? MRED_VRED { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gelieferte Menge, Summe über gesamten Referenzzeitraum, laut VWK".
        /// </summary>
        [Column("MRED_VSUM")]
        public decimal? MRED_VSUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "VOK Kommentar zu Vorsatz".
        /// </summary>
        [Column("MRED_VVORS")]
        [Required]
        public string? MRED_VVORS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kontrollergebnis Antrag fristgerecht".
        /// </summary>
        [Column("MRED_VW1")]
        [Required]
        public bool? MRED_VW1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kontrollergebnis Milcherzeugernachweis liegt vor".
        /// </summary>
        [Column("MRED_VW2")]
        [Required]
        public bool? MRED_VW2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kontrollergebnis Antragsunterlagen komplett vorliegend (Milchabrechnungen)".
        /// </summary>
        [Column("MRED_VW3")]
        [Required]
        public bool? MRED_VW3 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kontrollergebnis Angaben zum Referenzzeitraum stimmen mit Papierunterlagen überein".
        /// </summary>
        [Column("MRED_VW4")]
        [Required]
        public bool? MRED_VW4 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kontrollergebnis Sonstiger Ablehnungsgrund".
        /// </summary>
        [Column("MRED_VWABL")]
        [Required]
        public string? MRED_VWABL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kontrollergebnis Grund der Abweichung".
        /// </summary>
        [Column("MRED_VWABW")]
        [Required]
        public int? MRED_VWABW { get; set; }

        /// <summary>
        /// Gets or sets the value of "Verwaltungskontrolle zum Zahlungsantrag OK, Auszahlung möglich".
        /// </summary>
        [Column("MRED_VWZOK")]
        [Required]
        public bool? MRED_VWZOK { get; set; }

        /// <summary>
        /// Gets or sets the value of "Eingangszeitpunkt des Förderantrags, festgestellt".
        /// </summary>
        [Column("MRED_VW_TS")]
        [Required]
        public DateTime? MRED_VW_TS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gelieferte Menge im 1. Monat des Referenzzeitraums, laut VWK oder ggf. Antrag".
        /// </summary>
        [Column("MRED_XV1")]
        public decimal? MRED_XV1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gelieferte Menge im 2. Monat des Referenzzeitraums, laut VWK oder ggf. Antrag".
        /// </summary>
        [Column("MRED_XV2")]
        public decimal? MRED_XV2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gelieferte Menge im 3. Monat des Referenzzeitraums, laut VWK oder ggf. Antrag".
        /// </summary>
        [Column("MRED_XV3")]
        public decimal? MRED_XV3 { get; set; }

        /// <summary>
        /// Gets the value of "Letzter Änderungszeitpunkt des Zahlungsantrags".
        /// </summary>
        /// <remarks>
        /// momentan immaktueller Speicherzeitpunkt (SYS_VON)
        /// </remarks>
        [Column("MRED_ZA_TS")]
        public DateTime? MRED_ZA_TS { get; set; }

        /// <summary>
        /// Gets or sets the value of "VOK-Auswahlgrund".
        /// </summary>
        [Column("VOK_AGRUND")]
        public int? VOK_AGRUND { get; set; }

        /// <summary>
        /// Gets or sets the value of "In VOK ermittelte korrekte Liefermenge des Reduktionszeitraums".
        /// </summary>
        [Column("MRED_VOSUM")]
        public decimal? MRED_VOSUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gelieferte Menge, Summe über gesamten Referenzzeitraum, laut VWK oder ggf. Antrag".
        /// </summary>
        [Column("MRED_XSUM")]
        public decimal? MRED_XSUM { get; set; }

    }
}
