// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Betriebsindividuelle Daten zum Rind
    /// </summary>
    [Entity("RINDDATA")]
    public class RINDDATA
    {
        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ohrmarke".
        /// </summary>
        /// <remarks>
        /// IDENTIFICATION NUMBER
        /// </remarks>
        [Column("LOM")]
        [Required]
        public decimal? LOM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer des Unternehmens nach VVVO".
        /// </summary>
        /// <remarks>
        /// VVVO-UN zur BS oder Betrieb selbst wenn keine BS
        /// </remarks>
        [Column("BNR15_UNVV")]
        [Required]
        public decimal? BNR15_UNVV { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Individuelle Bemerkung".
        /// </summary>
        [Column("RD_BEMERK")]
        [Required]
        public string? RD_BEMERK { get; set; }

        /// <summary>
        /// Gets or sets the value of "Individuelle Angabe eines Datums, für betriebliche Verwendung".
        /// </summary>
        [Column("RD_DATUM")]
        public DateOnly? RD_DATUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Individuelle Nutzungsangabe".
        /// </summary>
        [Column("RD_INUTZ")]
        public int? RD_INUTZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bezeichnung für Betriebsteil, Herde oder Gruppe".
        /// </summary>
        [Column("RD_TEILBEZ")]
        [Required]
        public string? RD_TEILBEZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nummer für Betriebsteil, Herde oder Gruppe".
        /// </summary>
        [Column("RD_TEILNR")]
        public int? RD_TEILNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Individuelle Angabe einer Dezimalzahl, für betriebliche Verwendung".
        /// </summary>
        [Column("RD_WERTD")]
        public decimal? RD_WERTD { get; set; }

        /// <summary>
        /// Gets or sets the value of "Individuelle Angabe einer Ganzzahl, für betriebliche Verwendung".
        /// </summary>
        [Column("RD_WERTG")]
        public Int64? RD_WERTG { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "Satzstatus".
        /// </summary>
        /// <remarks>
        /// Systemstatus des Satzes
        /// </remarks>
        [Column("SYS_STAT")]
        public int? SYS_STAT { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Stallnummer oder alternativ Tiername".
        /// </summary>
        [Column("RD_STALLNR")]
        public string? RD_STALLNR { get; set; }

    }
}
