// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Salmonellen Untersuchungsauftrag
    /// </summary>
    [Entity("SALM_AUF")]
    public class SALM_AUF
    {
        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tierzahl in Stalleinheit zum Zeitpunkt der Probenahme".
        /// </summary>
        [Column("SA_ANZ")]
        public int? SA_ANZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Durchgangsbeginn, Einstalldatum".
        /// </summary>
        /// <remarks>
        /// Erster Tag
        /// </remarks>
        [Column("SA_DG_STA")]
        [Required]
        public DateOnly? SA_DG_STA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Untersuchungsgrund".
        /// </summary>
        [Column("SA_GRND")]
        [Required]
        public int? SA_GRND { get; set; }

        /// <summary>
        /// Gets or sets the value of "Untersuchungsmaterial".
        /// </summary>
        [Column("SA_MAT")]
        [Required]
        public int? SA_MAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Probenahmedatum".
        /// </summary>
        [Column("SA_N_DAT")]
        [Required]
        public DateOnly? SA_N_DAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nummer der Stalleinheit".
        /// </summary>
        [Column("SA_STNR")]
        [Required]
        public Int64? SA_STNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anzahl der Einzelproben".
        /// </summary>
        [Column("SA_UNT_ANZ")]
        public Int64? SA_UNT_ANZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Untersuchungslabor".
        /// </summary>
        /// <remarks>
        /// Betriebsnr des Untersuchungslabor oder -anstalt
        /// </remarks>
        [Column("UNTS_BNR15")]
        public decimal? UNTS_BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Globally Unique Identifier".
        /// </summary>
        /// <remarks>
        /// Format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (lower case)
        /// </remarks>
        [Column("GUID")]
        public string? GUID { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldeweg".
        /// </summary>
        /// <remarks>
        /// Meldeweg (Post,IVR,IN...)
        /// </remarks>
        [Column("MELD_WG")]
        public int? MELD_WG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Alter der Herde in Tagen".
        /// </summary>
        [Column("SA_ALTER")]
        public int? SA_ALTER { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nutzungart, Nutzungsrichtung".
        /// </summary>
        [Column("SA_FORM")]
        public int? SA_FORM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Haltungsart, Haltungsform".
        /// </summary>
        [Column("SA_HALTART")]
        public int? SA_HALTART { get; set; }

        /// <summary>
        /// Gets or sets the value of "Einsatz von Salmonella-Lebendimpfstoff".
        /// </summary>
        [Column("SA_IMPF")]
        public int? SA_IMPF { get; set; }

        /// <summary>
        /// Gets or sets the value of "Impfdatum".
        /// </summary>
        [Column("SA_IMP_DAT")]
        public DateOnly? SA_IMP_DAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Probenkennzeichnung".
        /// </summary>
        [Column("SA_PR_KENN")]
        public string? SA_PR_KENN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bemerkung".
        /// </summary>
        [Column("SA_UA_BEM")]
        public string? SA_UA_BEM { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "Satzstatus".
        /// </summary>
        /// <remarks>
        /// Systemstatus des Satzes
        /// </remarks>
        [Column("SYS_STAT")]
        public int? SYS_STAT { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

    }
}
