// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Eingeleitete Maßnahmen der zuständigen Behörde, u.a. Betriebssperre durch Veterinäre
    /// </summary>
    [Entity("SPERR_VET")]
    public class SPERR_VET
    {
        /// <summary>
        /// Gets or sets the value of "Vorgang J/N, wenn Tier  innerhalb SO verbracht wird, beim Zugang".
        /// </summary>
        /// <remarks>
        /// soll Vorgang generiert werden, wenn Tier innerhalb SO verbracht wird, beim Zugang
        /// </remarks>
        [Column("V_OUT_SO_Z")]
        public bool? V_OUT_SO_Z { get; set; }

        /// <summary>
        /// Gets or sets the value of "Sperrgrund, laut TSN".
        /// </summary>
        /// <remarks>
        /// Sperrgrund / Restriktionszonen, laut TSN
        /// </remarks>
        [Column("TSN_SP_GRN")]
        [Required]
        public int? TSN_SP_GRN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ohrmarke".
        /// </summary>
        /// <remarks>
        /// IDENTIFICATION NUMBER
        /// </remarks>
        [Column("LOM")]
        [Required]
        public decimal? LOM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorgang J/N, wenn Tier  innerhalb SO verbracht wird, beim Abgeber".
        /// </summary>
        /// <remarks>
        /// soll Vorgang generiert werden, wenn Tier innerhalb SO verbracht wird, beim Abgeber
        /// </remarks>
        [Column("V_OUT_SO_A")]
        public bool? V_OUT_SO_A { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tierart, Veterinärsperre".
        /// </summary>
        [Column("TIERART_VS")]
        [Required]
        public int? TIERART_VS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Datum der Maßnahme".
        /// </summary>
        /// <remarks>
        /// Datum wann die Maßnahme eingeleitet wurde
        /// </remarks>
        [Column("VET_MA_DAT")]
        [Required]
        public DateOnly? VET_MA_DAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorgang J/N, wenn Tier nach außerhalb SO zur Haltung verbracht, beim Abgeber".
        /// </summary>
        /// <remarks>
        /// soll Vorgang generiert werden, wenn Tier nach außerhalb SO zur Haltung verbracht, beim Abgeber
        /// </remarks>
        [Column("V_OUT_HA_A")]
        public bool? V_OUT_HA_A { get; set; }

        /// <summary>
        /// Gets or sets the value of "Beginn der Sperre".
        /// </summary>
        /// <remarks>
        /// Datum des Beginns der Sperre
        /// </remarks>
        [Column("SPERR_VON")]
        public DateOnly? SPERR_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorgang J/N, wenn Tier nach außerhalb SO zur Haltung verbracht, beim Zugang".
        /// </summary>
        /// <remarks>
        /// soll Vorgang generiert werden, wenn Tier nach außerhalb SO zur Haltung verbracht, beim Zugang
        /// </remarks>
        [Column("V_OUT_HA_Z")]
        public bool? V_OUT_HA_Z { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ende der Sperre".
        /// </summary>
        /// <remarks>
        /// Datum des Endes der Sperre, ggf. 31.12.2100 wenn unbegrenzt
        /// </remarks>
        [Column("SPERR_BIS")]
        public DateOnly? SPERR_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Sperre kostenpflichtig".
        /// </summary>
        /// <remarks>
        /// ist Bescheid/Anordnung kostenpflichtig
        /// </remarks>
        [Column("SPERR_KOST")]
        [Required]
        public int? SPERR_KOST { get; set; }

        /// <summary>
        /// Gets or sets the value of "TSN Seuchenobjekt-Nummer".
        /// </summary>
        /// <remarks>
        /// TSN Seuchenobjekt-Nummer
        /// </remarks>
        [Column("TSN_SO_NR")]
        [Required]
        public string? TSN_SO_NR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Maßnahme der Veterinärbehörde".
        /// </summary>
        /// <remarks>
        /// Maßnahme zum Abstellen von Mängeln oder Ahndung von Verstößen
        /// </remarks>
        [Column("VET_MASSN")]
        [Required]
        public int? VET_MASSN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorgang J/N, wenn Tier nach außerhalb SO zur Schlachtung verbracht, beim Abgeber".
        /// </summary>
        /// <remarks>
        /// soll Vorgang generiert werden, wenn Tier nach außerhalb SO zur Schlachtung verbracht, beim Abgeber
        /// </remarks>
        [Column("V_OUT_SC_A")]
        public bool? V_OUT_SC_A { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorgang J/N, wenn Tier nach außerhalb SO zur Schlachtung verbracht, beim Zugang".
        /// </summary>
        /// <remarks>
        /// soll Vorgang generiert werden, wenn Tier nach außerhalb SO zur Schlachtung verbracht, beim Zugang
        /// </remarks>
        [Column("V_OUT_SC_Z")]
        public bool? V_OUT_SC_Z { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorgang J/N, wenn Tier rein kommt, beim Abgeber".
        /// </summary>
        /// <remarks>
        /// soll Vorgang generiert werden, wenn Tier in SO hineinkommt, beim Abgeber
        /// </remarks>
        [Column("V_IN_A")]
        public bool? V_IN_A { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorgang J/N, wenn Tier rein kommt, beim Zugang".
        /// </summary>
        /// <remarks>
        /// soll Vorgang generiert werden, wenn Tier in SO hineinkommt, beim Zugang
        /// </remarks>
        [Column("V_IN_Z")]
        public bool? V_IN_Z { get; set; }

        /// <summary>
        /// Gets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets the value of "Meldeweg".
        /// </summary>
        /// <remarks>
        /// Meldeweg (Post,IVR,IN...)
        /// </remarks>
        [Column("MELD_WG")]
        public int? MELD_WG { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

    }
}
