// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Landkreis und Gemeinde, primär Veröffentlichung Zahlungen EU-Agrarfonds
    /// </summary>
    [Entity("SYS_LKRGMD")]
    public class SYS_LKRGMD
    {
        /// <summary>
        /// Gets or sets the value of "Bundesland".
        /// </summary>
        /// <remarks>
        /// Bundesland-Schlüssel
        /// </remarks>
        [Column("BLAND")]
        [Required]
        public int? BLAND { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gemeinde".
        /// </summary>
        /// <remarks>
        /// in der Regel 3stellig, ggf. 0 bei Kreisfreinen Gebieten
        /// </remarks>
        [Column("GDE")]
        [Required]
        public int? GDE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Landkreis".
        /// </summary>
        /// <remarks>
        /// in der Regel 3stellig, ggf. inklusive Regierungsbezirk
        /// </remarks>
        [Column("LKR")]
        [Required]
        public int? LKR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Landkreis/Gemeinde Bezeichnung".
        /// </summary>
        [Column("LKRGDE_BEZ")]
        [Required]
        public string? LKRGDE_BEZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Endezeitpunkt".
        /// </summary>
        [Column("LKRGDE_BIS")]
        [Required]
        public DateTime? LKRGDE_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Übergeordneter Landkreis".
        /// </summary>
        /// <remarks>
        /// ggf. 0
        /// </remarks>
        [Column("LKRGDE_ULK")]
        [Required]
        public int? LKRGDE_ULK { get; set; }

        /// <summary>
        /// Gets or sets the value of "Beginnzeitpunkt".
        /// </summary>
        [Column("LKRGDE_VON")]
        [Required]
        public DateTime? LKRGDE_VON { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldeweg".
        /// </summary>
        /// <remarks>
        /// Meldeweg (Post,IVR,IN...)
        /// </remarks>
        [Column("MELD_WG")]
        public int? MELD_WG { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Globally Unique Identifier".
        /// </summary>
        /// <remarks>
        /// Format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (lower case)
        /// </remarks>
        [Column("GUID")]
        public string? GUID { get; set; }

    }
}
