// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Schaf/Ziegen Produktionsrichtung für Statistik und Veterinärbelange
    /// </summary>
    [Entity("SZ_PROD")]
    public class SZ_PROD
    {
        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Mast (Ziegen)".
        /// </summary>
        [Column("SZ_PR_MA_Z")]
        public bool? SZ_PR_MA_Z { get; set; }

        /// <summary>
        /// Gets or sets the value of "Milch (Ziegen)".
        /// </summary>
        [Column("SZ_PR_MI_Z")]
        public bool? SZ_PR_MI_Z { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zucht (Ziegen)".
        /// </summary>
        [Column("SZ_PR_ZU_Z")]
        public bool? SZ_PR_ZU_Z { get; set; }

        /// <summary>
        /// Gets or sets the value of "Mast (Schafe)".
        /// </summary>
        [Column("SZ_PR_MA_S")]
        public bool? SZ_PR_MA_S { get; set; }

        /// <summary>
        /// Gets or sets the value of "Milch (Schafe)".
        /// </summary>
        [Column("SZ_PR_MI_S")]
        public bool? SZ_PR_MI_S { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zucht (Schafe)".
        /// </summary>
        [Column("SZ_PR_ZU_S")]
        public bool? SZ_PR_ZU_S { get; set; }

        /// <summary>
        /// Gets or sets the value of "Endezeitpunkt Produktionsrichtung".
        /// </summary>
        [Column("PROD_BIS")]
        [Required]
        public DateTime? PROD_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Beginnzeitpunkt Produktionsrichtung".
        /// </summary>
        [Column("PROD_VON")]
        [Required]
        public DateTime? PROD_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets the value of "Satzstatus".
        /// </summary>
        /// <remarks>
        /// Systemstatus des Satzes
        /// </remarks>
        [Column("SYS_STAT")]
        public int? SYS_STAT { get; set; }

    }
}
