// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Arzneimittel - [Achtung diese Daten unterliegen speziellen Copyrightbestimmungen des BfArM]
    /// </summary>
    [Entity("TAM_ARZN")]
    public class TAM_ARZN
    {
        /// <summary>
        /// Gets or sets the value of "Arzneimittel-Maßeinheit".
        /// </summary>
        [Column("TAMA_AME")]
        [Required]
        public int? TAMA_AME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Endezeitpunkt Arzneimittel".
        /// </summary>
        [Column("TAMA_BIS")]
        [Required]
        public DateTime? TAMA_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anmeldernummer".
        /// </summary>
        [Column("TAMA_PNR")]
        [Required]
        public string? TAMA_PNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Beginnzeitpunkt Arzneimittel".
        /// </summary>
        [Column("TAMA_VON")]
        [Required]
        public DateTime? TAMA_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zulassungsnummer".
        /// </summary>
        [Column("TAMA_ZNR")]
        [Required]
        public string? TAMA_ZNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldeweg".
        /// </summary>
        /// <remarks>
        /// Meldeweg (Post,IVR,IN...)
        /// </remarks>
        [Column("MELD_WG")]
        public int? MELD_WG { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets or sets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        [Required]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anzahl antibakteriell wirksamer Stoffe".
        /// </summary>
        /// <remarks>
        /// (Antibiotika-Wirkstoffe und Chemotherapeutika)
        /// </remarks>
        [Column("TAMA_AWANZ")]
        [Required]
        public int? TAMA_AWANZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Arzneimittelname".
        /// </summary>
        [Column("TAMA_NAME")]
        [Required]
        public string? TAMA_NAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Pharmazeutischer Unternehmer".
        /// </summary>
        [Column("TAMA_PNAME")]
        [Required]
        public string? TAMA_PNAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Wirkkoeffizient".
        /// </summary>
        /// <remarks>
        /// keine einfache Multiplikation, sondern nach Gruppen
        /// </remarks>
        [Column("TAMA_WKOEF")]
        [Required]
        public int? TAMA_WKOEF { get; set; }

        /// <summary>
        /// Gets or sets the value of "Arzneimittel geeignet für Huhn".
        /// </summary>
        [Column("TAMA_HUHN")]
        [Required]
        public bool? TAMA_HUHN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Arzneimittel geeignet für Pute".
        /// </summary>
        [Column("TAMA_PUTE")]
        [Required]
        public bool? TAMA_PUTE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Arzneimittel geeignet für Rind".
        /// </summary>
        [Column("TAMA_RIND")]
        [Required]
        public bool? TAMA_RIND { get; set; }

        /// <summary>
        /// Gets or sets the value of "Arzneimittel geeignet für Schwein".
        /// </summary>
        [Column("TAMA_SCHW")]
        [Required]
        public bool? TAMA_SCHW { get; set; }

    }
}
