// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Benutzerprofil TAM Detail, Sicht für Dritten (mit Änderung)
    /// </summary>
    [Entity("TAM_PDETD")]
    public class TAM_PDETD
    {
        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer Dritter".
        /// </summary>
        /// <remarks>
        /// speziell im Bereich Tierarzneimittel (TAM)
        /// </remarks>
        [Column("BNR15_DR")]
        [Required]
        public decimal? BNR15_DR { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldeweg".
        /// </summary>
        /// <remarks>
        /// Meldeweg (Post,IVR,IN...)
        /// </remarks>
        [Column("MELD_WG")]
        public int? MELD_WG { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Antibiotika-Einsatz Masthuhn".
        /// </summary>
        [Column("TAMP_AB_H1")]
        public int? TAMP_AB_H1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Antibiotika-Einsatz Mastpute".
        /// </summary>
        [Column("TAMP_AB_P1")]
        public int? TAMP_AB_P1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Antibiotika-Einsatz Mastkalb".
        /// </summary>
        [Column("TAMP_AB_R1")]
        public int? TAMP_AB_R1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Antibiotika-Einsatz Mastrind".
        /// </summary>
        [Column("TAMP_AB_R2")]
        public int? TAMP_AB_R2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Antibiotika-Einsatz Mastferkel".
        /// </summary>
        [Column("TAMP_AB_S1")]
        public int? TAMP_AB_S1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Antibiotika-Einsatz Mastschwein".
        /// </summary>
        [Column("TAMP_AB_S2")]
        public int? TAMP_AB_S2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Durchschnitt Masthuhn".
        /// </summary>
        [Column("TAMP_DU_H1")]
        public int? TAMP_DU_H1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Durchschnitt Mastpute".
        /// </summary>
        [Column("TAMP_DU_P1")]
        public int? TAMP_DU_P1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Durchschnitt Mastkalb".
        /// </summary>
        [Column("TAMP_DU_R1")]
        public int? TAMP_DU_R1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Durchschnitt Mastrind".
        /// </summary>
        [Column("TAMP_DU_R2")]
        public int? TAMP_DU_R2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Durchschnitt Mastferkel".
        /// </summary>
        [Column("TAMP_DU_S1")]
        public int? TAMP_DU_S1 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Durchschnitt Mastschwein".
        /// </summary>
        [Column("TAMP_DU_S2")]
        public int? TAMP_DU_S2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "TAM-Profildetail, Freigabe der Daten für Amt".
        /// </summary>
        [Column("TAMP_D_AFR")]
        [Required]
        public bool? TAMP_D_AFR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kalenderhalbjahr".
        /// </summary>
        [Column("TAM_PERIOD")]
        [Required]
        public int? TAM_PERIOD { get; set; }

    }
}
