// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Arzneimittel Abgabe und Anwendung
    /// </summary>
    [Entity("TAM_XABAW")]
    public class TAM_XABAW
    {
        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer Tierhalter".
        /// </summary>
        /// <remarks>
        /// speziell im Bereich Tierarzneimittel (TAM)
        /// </remarks>
        [Column("BNR15_HA")]
        [Required]
        public decimal? BNR15_HA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Arzneimittelname".
        /// </summary>
        [Column("TAMA_NAME")]
        [Required]
        public string? TAMA_NAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zulassungsnummer".
        /// </summary>
        [Column("TAMA_ZNR")]
        [Required]
        public string? TAMA_ZNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Arzneimittel Anwendung oder Abgabe".
        /// </summary>
        [Column("TAMX_ABAW")]
        [Required]
        public int? TAMX_ABAW { get; set; }

        /// <summary>
        /// Gets or sets the value of "Arzneimittelmeldung für die Behörde zugänglich".
        /// </summary>
        [Column("TAMX_ABDB")]
        [Required]
        public int? TAMX_ABDB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anwendungsmenge, ersatzweise Abgabemenge".
        /// </summary>
        /// <remarks>
        /// Menge des Arzneimittels
        /// </remarks>
        [Column("TAMX_AWMEN")]
        [Required]
        public decimal? TAMX_AWMEN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kalenderhalbjahr".
        /// </summary>
        [Column("TAM_PERIOD")]
        [Required]
        public int? TAM_PERIOD { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldeweg".
        /// </summary>
        /// <remarks>
        /// Meldeweg (Post,IVR,IN...)
        /// </remarks>
        [Column("MELD_WG")]
        public int? MELD_WG { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nutzungsart (nach § 58a AMG), erweitert".
        /// </summary>
        /// <remarks>
        /// (ggf. mit spezifischen Erweiterungen)
        /// </remarks>
        [Column("TAMB_FORM")]
        [Required]
        public int? TAMB_FORM { get; set; }

        /// <summary>
        /// Gets or sets the value of "weitere Behandlungsanweisungen an den Tierhalter".
        /// </summary>
        /// <remarks>
        /// (soweit erforderlich)
        /// </remarks>
        [Column("TAMX_ANWEI")]
        [Required]
        public string? TAMX_ANWEI { get; set; }

        /// <summary>
        /// Gets or sets the value of "Art der Anwendung / Verabreichung".
        /// </summary>
        [Column("TAMX_AWART")]
        [Required]
        public int? TAMX_AWART { get; set; }

        /// <summary>
        /// Gets or sets the value of "Maßeinheit für Anwendungsmenge".
        /// </summary>
        [Column("TAMX_AW_ME")]
        [Required]
        public int? TAMX_AW_ME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Belegart".
        /// </summary>
        [Column("TAMX_BEART")]
        [Required]
        public int? TAMX_BEART { get; set; }

        /// <summary>
        /// Gets or sets the value of "Dauer der Anwendung (Behandlungstage)".
        /// </summary>
        [Column("TAMX_BEHAT")]
        [Required]
        public int? TAMX_BEHAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Chargenbezeichnung".
        /// </summary>
        [Column("TAMX_CHARG")]
        [Required]
        public string? TAMX_CHARG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Diagnose".
        /// </summary>
        [Column("TAMX_DIAGN")]
        [Required]
        public string? TAMX_DIAGN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Dosierung des Arzneimittels pro Tier und Tag".
        /// </summary>
        [Column("TAMX_DOSIS")]
        public decimal? TAMX_DOSIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Maßeinheit für Dosis pro Tier und Tag".
        /// </summary>
        [Column("TAMX_DO_ME")]
        public int? TAMX_DO_ME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Identität".
        /// </summary>
        [Column("TAMX_IDENT")]
        [Required]
        public string? TAMX_IDENT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kennzeichen für Korrekturbeleg".
        /// </summary>
        [Column("TAMX_KORR")]
        [Required]
        public int? TAMX_KORR { get; set; }

        /// <summary>
        /// Gets or sets the value of "laufende Nummer pro Tierart/Nutzungsart wenn mehr als ein Eintrag".
        /// </summary>
        [Column("TAMX_LFNR")]
        [Required]
        public int? TAMX_LFNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nummer AuA-Beleg".
        /// </summary>
        [Column("TAMX_NRAUA")]
        [Required]
        public string? TAMX_NRAUA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Name der anwendenden Person".
        /// </summary>
        [Column("TAMX_PERS")]
        [Required]
        public string? TAMX_PERS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Standort (wenn für Identität erforderlich)".
        /// </summary>
        [Column("TAMX_STORT")]
        [Required]
        public string? TAMX_STORT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anzahl Tiere bei dieser Behandlung".
        /// </summary>
        [Column("TAMX_TIANZ")]
        [Required]
        public Int64? TAMX_TIANZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tierart".
        /// </summary>
        /// <remarks>
        /// freie Eingabe, insbesondere für sonstige Tiere die nicht der AMG-Meldepflicht unterliegen
        /// </remarks>
        [Column("TAMX_TIART")]
        [Required]
        public string? TAMX_TIART { get; set; }

        /// <summary>
        /// Gets or sets the value of "Wartezeit in Tagen (Eier)".
        /// </summary>
        [Column("TAMX_WARTE")]
        public int? TAMX_WARTE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Wartezeit in Tagen (Fleisch)".
        /// </summary>
        [Column("TAMX_WARTF")]
        public int? TAMX_WARTF { get; set; }

        /// <summary>
        /// Gets or sets the value of "Wartezeit in Tagen (Milch)".
        /// </summary>
        [Column("TAMX_WARTM")]
        public int? TAMX_WARTM { get; set; }

        /// <summary>
        /// Gets or sets the value of "Wartezeit in Tagen (allgemein als Text)".
        /// </summary>
        [Column("TAMX_WARTT")]
        [Required]
        public string? TAMX_WARTT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kennzeichen ob Daten bei Meldung für AMG beabsichtigt sind".
        /// </summary>
        [Column("TAMX_AMG")]
        [Required]
        public int? TAMX_AMG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Verantwortlicher Tierarzt".
        /// </summary>
        /// <remarks>
        /// zuständiger Hof- oder Privat-Tierarzt, ggf. Veterinär
        /// </remarks>
        [Column("BNR15_TA")]
        public decimal? BNR15_TA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Wirkungstage (Funktion aus Behandlungstage und Wirkkoeffizient)".
        /// </summary>
        [Column("TAMX_WIRKT")]
        [Required]
        public int? TAMX_WIRKT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Globally Unique Identifier".
        /// </summary>
        /// <remarks>
        /// Format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (lower case)
        /// </remarks>
        [Column("GUID")]
        public string? GUID { get; set; }

        /// <summary>
        /// Gets or sets the value of "Datum der Abgabe".
        /// </summary>
        [Column("TAMX_ABDAT")]
        public DateOnly? TAMX_ABDAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Abgabemenge".
        /// </summary>
        /// <remarks>
        /// abgegebene Menge des Arzneimittels
        /// </remarks>
        [Column("TAMX_ABMEN")]
        public decimal? TAMX_ABMEN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Maßeinheit für Abgabemenge".
        /// </summary>
        /// <remarks>
        /// Pflicht für TA
        /// </remarks>
        [Column("TAMX_AB_ME")]
        public int? TAMX_AB_ME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Datum der Anwendung, bzw. Abgabe".
        /// </summary>
        /// <remarks>
        /// im AuA-Beleg bezeichnet als Zeitpunkt der Anwendung
        /// </remarks>
        [Column("TAMX_AWDAT")]
        [Required]
        public DateOnly? TAMX_AWDAT { get; set; }

    }
}
