// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Ermittelte Handelskontakte (statische Werte)
    /// </summary>
    [Entity("TI_KONTAKT")]
    public class TI_KONTAKT
    {
        /// <summary>
        /// Gets or sets the value of "Jahr".
        /// </summary>
        /// <remarks>
        /// Jahresangabe, vierstellig
        /// </remarks>
        [Column("JAHR")]
        [Required]
        public int? JAHR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "letztes Datum, das bei der Berechnung der statischen Werte berücksichtigt wurde".
        /// </summary>
        /// <remarks>
        /// ca. 4 Wochen vor heute
        /// </remarks>
        [Column("TI_KON_DAT")]
        [Required]
        public DateOnly? TI_KON_DAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Jahresdurchschnitt der statischen Wochenwerte, Rinder".
        /// </summary>
        /// <remarks>
        /// Handelskontakte, unabhängig von Seuchen-Startbetrieben, gleitender Durchschnitt aus 52 Wochen
        /// </remarks>
        [Column("RI_KON_DUR")]
        [Required]
        public Int64? RI_KON_DUR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Standardabweichung der statischen Wochenwerte, Rinder".
        /// </summary>
        [Column("RI_KON_STA")]
        [Required]
        public Int64? RI_KON_STA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Januar, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_JAN")]
        [Required]
        public Int64? RI_KON_JAN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Februar, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_FEB")]
        [Required]
        public Int64? RI_KON_FEB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für März, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_MRZ")]
        [Required]
        public Int64? RI_KON_MRZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für April, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_APR")]
        [Required]
        public Int64? RI_KON_APR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Mai, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_MAI")]
        [Required]
        public Int64? RI_KON_MAI { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Juni, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_JUN")]
        [Required]
        public Int64? RI_KON_JUN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Juli, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_JUL")]
        [Required]
        public Int64? RI_KON_JUL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für August, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_AUG")]
        [Required]
        public Int64? RI_KON_AUG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für September, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_SEP")]
        [Required]
        public Int64? RI_KON_SEP { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Oktober, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_OKT")]
        [Required]
        public Int64? RI_KON_OKT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für November, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_NOV")]
        [Required]
        public Int64? RI_KON_NOV { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Dezember, Rinder".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("RI_KON_DEZ")]
        [Required]
        public Int64? RI_KON_DEZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Jahresdurchschnitt der statischen Wochenwerte, Schweine".
        /// </summary>
        /// <remarks>
        /// Handelskontakte, unabhängig von Seuchen-Startbetrieben, gleitender Durchschnitt aus 52 Wochen
        /// </remarks>
        [Column("S_KON_DUR")]
        [Required]
        public Int64? S_KON_DUR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Standardabweichung der statischen Wochenwerte, Schweine".
        /// </summary>
        [Column("S_KON_STA")]
        [Required]
        public Int64? S_KON_STA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Januar, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_JAN")]
        [Required]
        public Int64? S_KON_JAN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Februar,Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_FEB")]
        [Required]
        public Int64? S_KON_FEB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für März, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_MRZ")]
        [Required]
        public Int64? S_KON_MRZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für April, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_APR")]
        [Required]
        public Int64? S_KON_APR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Mai, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_MAI")]
        [Required]
        public Int64? S_KON_MAI { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Juni, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_JUN")]
        [Required]
        public Int64? S_KON_JUN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Juli, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_JUL")]
        [Required]
        public Int64? S_KON_JUL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für August, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_AUG")]
        [Required]
        public Int64? S_KON_AUG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für September, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_SEP")]
        [Required]
        public Int64? S_KON_SEP { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Oktober, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_OKT")]
        [Required]
        public Int64? S_KON_OKT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für November, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_NOV")]
        [Required]
        public Int64? S_KON_NOV { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Dezember, Schweine".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("S_KON_DEZ")]
        [Required]
        public Int64? S_KON_DEZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Jahresdurchschnitt der statischen Wochenwerte, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// Handelskontakte, unabhängig von Seuchen-Startbetrieben, gleitender Durchschnitt aus 52 Wochen
        /// </remarks>
        [Column("SZ_KON_DUR")]
        [Required]
        public Int64? SZ_KON_DUR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Standardabweichung der statischen Wochenwerte, Schafe/Ziegen".
        /// </summary>
        [Column("SZ_KON_STA")]
        [Required]
        public Int64? SZ_KON_STA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Januar, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_JAN")]
        [Required]
        public Int64? SZ_KON_JAN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Februar,Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_FEB")]
        [Required]
        public Int64? SZ_KON_FEB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für März, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_MRZ")]
        [Required]
        public Int64? SZ_KON_MRZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für April, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_APR")]
        [Required]
        public Int64? SZ_KON_APR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Mai, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_MAI")]
        [Required]
        public Int64? SZ_KON_MAI { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Juni, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_JUN")]
        [Required]
        public Int64? SZ_KON_JUN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Juli, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_JUL")]
        [Required]
        public Int64? SZ_KON_JUL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für August, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_AUG")]
        [Required]
        public Int64? SZ_KON_AUG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für September, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_SEP")]
        [Required]
        public Int64? SZ_KON_SEP { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Oktober, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_OKT")]
        [Required]
        public Int64? SZ_KON_OKT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für November, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_NOV")]
        [Required]
        public Int64? SZ_KON_NOV { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Dezember, Schafe/Ziegen".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("SZ_KON_DEZ")]
        [Required]
        public Int64? SZ_KON_DEZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Jahresdurchschnitt der statischen Wochenwerte, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// Handelskontakte, unabhängig von Seuchen-Startbetrieben, gleitender Durchschnitt aus 52 Wochen
        /// </remarks>
        [Column("GE_KON_DUR")]
        [Required]
        public Int64? GE_KON_DUR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Standardabweichung der statischen Wochenwerte, Gemischtbetrieb".
        /// </summary>
        [Column("GE_KON_STA")]
        [Required]
        public Int64? GE_KON_STA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Januar, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_JAN")]
        [Required]
        public Int64? GE_KON_JAN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Februar,Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_FEB")]
        [Required]
        public Int64? GE_KON_FEB { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für März, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_MRZ")]
        [Required]
        public Int64? GE_KON_MRZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für April, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_APR")]
        [Required]
        public Int64? GE_KON_APR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Mai, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_MAI")]
        [Required]
        public Int64? GE_KON_MAI { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Juni, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_JUN")]
        [Required]
        public Int64? GE_KON_JUN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Juli, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_JUL")]
        [Required]
        public Int64? GE_KON_JUL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für August, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_AUG")]
        [Required]
        public Int64? GE_KON_AUG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für September, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_SEP")]
        [Required]
        public Int64? GE_KON_SEP { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Oktober, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_OKT")]
        [Required]
        public Int64? GE_KON_OKT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für November, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_NOV")]
        [Required]
        public Int64? GE_KON_NOV { get; set; }

        /// <summary>
        /// Gets or sets the value of "Statisches Maß für Dezember, Gemischtbetrieb".
        /// </summary>
        /// <remarks>
        /// durchschnittl. wöchentl. Betriebskontakte des Monats
        /// </remarks>
        [Column("GE_KON_DEZ")]
        [Required]
        public Int64? GE_KON_DEZ { get; set; }

    }
}
