// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Anerkennung als Trichienen freies Haltungssystem
    /// </summary>
    [Entity("TRI_HSYS")]
    public class TRI_HSYS
    {
        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Globally Unique Identifier".
        /// </summary>
        /// <remarks>
        /// Format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (lower case)
        /// </remarks>
        [Column("GUID")]
        public string? GUID { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldedatum".
        /// </summary>
        /// <remarks>
        /// Datum des Meldeeingang
        /// </remarks>
        [Column("MELD_DAT")]
        public DateOnly? MELD_DAT { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldeweg".
        /// </summary>
        /// <remarks>
        /// Meldeweg (Post,IVR,IN...)
        /// </remarks>
        [Column("MELD_WG")]
        public int? MELD_WG { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Endezeitpunkt Anerkennung Trichinenfreiheit".
        /// </summary>
        /// <remarks>
        /// Endes der fachlichen Gültigkeit (identisch zu nächstem Beginn, oder 31.12.2100 wenn aktuell)
        /// </remarks>
        [Column("TRFAN_BIS")]
        [Required]
        public DateTime? TRFAN_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Erster Tag der Anerkennung Trichinenfreiheit".
        /// </summary>
        /// <remarks>
        /// abgeleitet aus TRFAN_VON, i.d.R. das selbe Datum
        /// </remarks>
        [Column("TRFAN_TGE")]
        public DateOnly? TRFAN_TGE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Letzter Tag der Anerkennung Trichinenfreiheit".
        /// </summary>
        /// <remarks>
        /// abgeleitet aus TRFAN_BIS, i.d.R. das Datum des Vortages (der letzte, komplett enthaltene Tag)
        /// </remarks>
        [Column("TRFAN_TGL")]
        public DateOnly? TRFAN_TGL { get; set; }

        /// <summary>
        /// Gets or sets the value of "Beginnzeitpunkt Anerkennung Trichinenfreiheit".
        /// </summary>
        /// <remarks>
        /// Beginns der fachlichen Gültigkeit
        /// </remarks>
        [Column("TRFAN_VON")]
        [Required]
        public DateTime? TRFAN_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Prüfbehörde".
        /// </summary>
        /// <remarks>
        /// Registriernummer der zuständigen Prüfbehörde
        /// </remarks>
        [Column("TRI_AMT")]
        [Required]
        public decimal? TRI_AMT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anerkennung Trichinenfreiheit".
        /// </summary>
        /// <remarks>
        /// Haltungssystem als Trichinen frei anerkannt
        /// </remarks>
        [Column("TRI_ANER")]
        [Required]
        public int? TRI_ANER { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bemerkung".
        /// </summary>
        /// <remarks>
        /// Bemerkungsfeld
        /// </remarks>
        [Column("TRI_BEM")]
        [Required]
        public string? TRI_BEM { get; set; }

    }
}
