// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Gewichte aus der Risikoanalyse als Grundlage für gemeinsame Vorortkontrolle
    /// </summary>
    [Entity("VOK_GEW")]
    public class VOK_GEW
    {
        /// <summary>
        /// Gets or sets the value of "Bestand Risikojahr".
        /// </summary>
        /// <remarks>
        /// Bestand zu Beginn des Risikojahres (31.12.RIS_JAHR - 1)
        /// </remarks>
        [Column("VG_BES_RJ")]
        [Required]
        public Int64? VG_BES_RJ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Parent-Betrieb".
        /// </summary>
        /// <remarks>
        /// Root-Betrieb bei Zuordnung
        /// </remarks>
        [Column("BNR15_P")]
        [Required]
        public decimal? BNR15_P { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anteil Vorgänge offen".
        /// </summary>
        /// <remarks>
        /// Vorgänge offen als Anteil an aktuellen Meldungen
        /// </remarks>
        [Column("VG_VRG_OFA")]
        [Required]
        public Int64? VG_VRG_OFA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Anteil Vorgänge insgesamt".
        /// </summary>
        /// <remarks>
        /// Vorgänge insgesamt als Anteil an aktuellen Meldungen
        /// </remarks>
        [Column("VG_VRG_GEA")]
        [Required]
        public Int64? VG_VRG_GEA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gewicht Gruppe 3".
        /// </summary>
        /// <remarks>
        /// Gewicht Gruppe 3 - Bestandsänderung
        /// </remarks>
        [Column("VG_G3_AEND")]
        [Required]
        public int? VG_G3_AEND { get; set; }

        /// <summary>
        /// Gets or sets the value of "Status Gezogen oder nicht".
        /// </summary>
        /// <remarks>
        /// Nicht gezogen, RIA, Zufall, gesetzt ...
        /// </remarks>
        [Column("VG_GEZOGEN")]
        [Required]
        public int? VG_GEZOGEN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gewicht Gruppe 7".
        /// </summary>
        /// <remarks>
        /// Gewicht Gruppe 7 - gesetztes Gewicht
        /// </remarks>
        [Column("VG_G7_SETZ")]
        [Required]
        public int? VG_G7_SETZ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gewicht Gruppe 2".
        /// </summary>
        /// <remarks>
        /// Gewicht Gruppe 2 - Anzahl Prämienanträge
        /// </remarks>
        [Column("VG_G2_PRAE")]
        [Required]
        public int? VG_G2_PRAE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gewicht Gruppe 4".
        /// </summary>
        /// <remarks>
        /// Gewicht Gruppe 4 - Vorortkontrollergebnisse
        /// </remarks>
        [Column("VG_G4_VOKE")]
        [Required]
        public int? VG_G4_VOKE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gewicht Gruppe 5".
        /// </summary>
        /// <remarks>
        /// Gewicht Gruppe 5 - Meldefristen und Fehlervorgänge
        /// </remarks>
        [Column("VG_G5_VORG")]
        [Required]
        public int? VG_G5_VORG { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gewicht Gruppe 6".
        /// </summary>
        /// <remarks>
        /// Gewicht Gruppe 6 - Gewicht aus Tiergesundheits- und Veterinäraspekten
        /// </remarks>
        [Column("VG_G6_VETA")]
        [Required]
        public int? VG_G6_VETA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gewicht Gruppe 1".
        /// </summary>
        /// <remarks>
        /// Gewicht Gruppe 1 - Meldung und Bestand
        /// </remarks>
        [Column("VG_G1_MELD")]
        [Required]
        public int? VG_G1_MELD { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bestandsveränderung".
        /// </summary>
        /// <remarks>
        /// Bestandsveränderung als %-Steigerung gegenüber Vorjahr
        /// </remarks>
        [Column("VG_BES_DTA")]
        [Required]
        public Int64? VG_BES_DTA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Jahr der Risikoanalyse (Kontrolljahr)".
        /// </summary>
        /// <remarks>
        /// Jahresangabe, vierstellig
        /// </remarks>
        [Column("RIS_JAHR")]
        [Required]
        public int? RIS_JAHR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bestand Vorjahr".
        /// </summary>
        /// <remarks>
        /// Bestand zu Beginn des Vorjahres (31.12.RIS_JAHR - 2)
        /// </remarks>
        [Column("VG_BES_VJ")]
        [Required]
        public Int64? VG_BES_VJ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Stornoanteil".
        /// </summary>
        /// <remarks>
        /// Stornoanteil
        /// </remarks>
        [Column("VG_STO_ANT")]
        [Required]
        public Int64? VG_STO_ANT { get; set; }

        /// <summary>
        /// Gets or sets the value of "VOK-Probleme".
        /// </summary>
        /// <remarks>
        /// Probleme bei VOK festgestellt
        /// </remarks>
        [Column("VG_VOK_PRB")]
        [Required]
        public Int64? VG_VOK_PRB { get; set; }

        /// <summary>
        /// Gets or sets the value of "VVVO-Meldungen storniert".
        /// </summary>
        /// <remarks>
        /// Anzahl VVVO-Meldungen storniert
        /// </remarks>
        [Column("VG_VV_ROS")]
        [Required]
        public Int64? VG_VV_ROS { get; set; }

        /// <summary>
        /// Gets or sets the value of "ist Nachfolger".
        /// </summary>
        /// <remarks>
        /// Betrieb ist aktuell Nachfolger
        /// </remarks>
        [Column("VG_IS_NACH")]
        [Required]
        public Int64? VG_IS_NACH { get; set; }

        /// <summary>
        /// Gets or sets the value of "Prämienbetrieb".
        /// </summary>
        /// <remarks>
        /// keine Prämie, selber Prämie, Mutter-UN oder Nachfolger mit Prämie
        /// </remarks>
        [Column("VG_PR_STAT")]
        [Required]
        public int? VG_PR_STAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorgänge insgesamt".
        /// </summary>
        /// <remarks>
        /// Vorgänge insgesamt
        /// </remarks>
        [Column("VG_VRG_GES")]
        [Required]
        public Int64? VG_VRG_GES { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tierprämienanträge Vorjahr".
        /// </summary>
        /// <remarks>
        /// Anzahl Tierprämienanträge im Vorjahr
        /// </remarks>
        [Column("VG_PR_VJ")]
        [Required]
        public Int64? VG_PR_VJ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Vorgänge offen".
        /// </summary>
        /// <remarks>
        /// Vorgänge offen
        /// </remarks>
        [Column("VG_VRG_OFF")]
        [Required]
        public Int64? VG_VRG_OFF { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tierprämienanträge Risikojahr".
        /// </summary>
        /// <remarks>
        /// Anzahl Tierprämienanträge im Risikojahr
        /// </remarks>
        [Column("VG_PR_RJ")]
        [Required]
        public Int64? VG_PR_RJ { get; set; }

        /// <summary>
        /// Gets or sets the value of "Gesamt-Gewicht".
        /// </summary>
        /// <remarks>
        /// Gesamt-Gewicht als Summe G1..G7
        /// </remarks>
        [Column("VG_GG_SUM")]
        [Required]
        public int? VG_GG_SUM { get; set; }

        /// <summary>
        /// Gets or sets the value of "VVVO-Meldungen aktuell".
        /// </summary>
        /// <remarks>
        /// Anzahl VVVO-Meldungen aktuell
        /// </remarks>
        [Column("VG_VV_ROA")]
        [Required]
        public Int64? VG_VV_ROA { get; set; }

        /// <summary>
        /// Gets or sets the value of "Antragszahl Steigerung gegenüber Vorjahr".
        /// </summary>
        /// <remarks>
        /// Änderung in Antragszahl als %-Steigerung gegenüber Vorjahr
        /// </remarks>
        [Column("VG_PR_DTA")]
        [Required]
        public Int64? VG_PR_DTA { get; set; }

    }
}
