// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Meldungen (erweiterte Version ab 07.2012)
    /// </summary>
    [Entity("XMELDUNGEN")]
    public class XMELDUNGEN
    {
        /// <summary>
        /// Gets or sets the value of "Entity".
        /// </summary>
        [Column("ENTITY")]
        [Required]
        public string? ENTITY { get; set; }

        /// <summary>
        /// Gets or sets the value of "DDE".
        /// </summary>
        [Column("DDE")]
        [Required]
        public string? DDE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Entityname".
        /// </summary>
        [Column("ENTITYNAME")]
        [Required]
        public string? ENTITYNAME { get; set; }

        /// <summary>
        /// Gets or sets the value of "Typ der Entität".
        /// </summary>
        /// <remarks>
        /// Gruppierung bez. Tier, Betrieb, Prämie ...
        /// </remarks>
        [Column("TYP")]
        [Required]
        public string? TYP { get; set; }

        /// <summary>
        /// Gets or sets the value of "Feldname mit BNR".
        /// </summary>
        /// <remarks>
        /// Names des Meldungs-Elements mit der BNR für Kompetenz-Prüfung
        /// </remarks>
        [Column("FELDBNR")]
        public string? FELDBNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "FeldNamen TS-Von, Kennzeichen für technnischs Historie (für aktuell, RS/Z und Delta)".
        /// </summary>
        /// <remarks>
        /// Meldungselemente mit Begin-Timestamp (hier technisch), mittels Komma getrennt
        /// </remarks>
        [Column("FELDVON")]
        public string? FELDVON { get; set; }

        /// <summary>
        /// Gets or sets the value of "FeldNamen TS-Bis, Kennzeichen für technnischs Historie (für aktuell, RS/Z und Delta)".
        /// </summary>
        /// <remarks>
        /// Meldungselemente mit Ende-Timestamp (hier technisch), mittels Komma getrennt
        /// </remarks>
        [Column("FELDBIS")]
        public string? FELDBIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "FeldNameLom".
        /// </summary>
        /// <remarks>
        /// Names des Meldungs-Elements mit der LOM für Vorgangsabfrage
        /// </remarks>
        [Column("FELDLOM")]
        public string? FELDLOM { get; set; }

        /// <summary>
        /// Gets or sets the value of "FeldNameDat".
        /// </summary>
        /// <remarks>
        /// Names des Meldungs-Elements mit dem Ereignisdatum
        /// </remarks>
        [Column("FELDDAT")]
        public string? FELDDAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "FeldNamen TS-Von, Kennzeichen für fachliche Historie (RS/F)".
        /// </summary>
        /// <remarks>
        /// Meldungselemente mit Begin-Timestamp (hier fachlich), mittels Komma getrennt
        /// </remarks>
        [Column("FELDVON2")]
        public string? FELDVON2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "FeldNamen TS-Bis, Kennzeichen für fachliche Historie (RS/F)".
        /// </summary>
        /// <remarks>
        /// Meldungselemente mit Ende-Timestamp (hier fachlich), mittels Komma getrennt
        /// </remarks>
        [Column("FELDBIS2")]
        public string? FELDBIS2 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Feldname Prämien-Kompetenz".
        /// </summary>
        /// <remarks>
        /// auf welche Spalte bei Kompetenz-Bereich P, Q (für Prämien/ZID) geprüft wird
        /// </remarks>
        [Column("FELDPKOMP")]
        public string? FELDPKOMP { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kennzeichen on HIT-Vollmacht für die Meldung gilt".
        /// </summary>
        [Column("VM_HIT")]
        [Required]
        public bool? VM_HIT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Kennzeichen on ZID-Vollmacht für die Meldung gilt".
        /// </summary>
        [Column("VM_ZID")]
        [Required]
        public bool? VM_ZID { get; set; }

        /// <summary>
        /// Gets or sets the value of "Alternative Feldnamen mit BNR, für Lesekompetenz".
        /// </summary>
        /// <remarks>
        /// mittels Komma getrennt
        /// </remarks>
        [Column("FELDBNRX")]
        [Required]
        public string? FELDBNRX { get; set; }

        /// <summary>
        /// Gets or sets the value of "Fachlich gültig von".
        /// </summary>
        /// <remarks>
        /// Timestamp ab wann der Satz fachlich gilt
        /// </remarks>
        [Column("FACH_VON")]
        [Required]
        public DateTime? FACH_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Fachlich gültig bis".
        /// </summary>
        /// <remarks>
        /// fachlich gültig bis oder aktuell (31.12.2100)
        /// </remarks>
        [Column("FACH_BIS")]
        [Required]
        public DateTime? FACH_BIS { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Satzstatus".
        /// </summary>
        /// <remarks>
        /// Systemstatus des Satzes
        /// </remarks>
        [Column("SYS_STAT")]
        public int? SYS_STAT { get; set; }

    }
}
