// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Zahlungsansprüche, Paketeigenschaft
    /// </summary>
    [Entity("ZA_PAKET")]
    public class ZA_PAKET
    {
        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zahlungsanspruchs-Land".
        /// </summary>
        /// <remarks>
        /// Land das den ZA ausgegeben hat. Dient mit Serie und Nr zur Identifikation.
        /// </remarks>
        [Column("ZA_LAND")]
        [Required]
        public int? ZA_LAND { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zahlunganspruchsintervall, externe Darstellung".
        /// </summary>
        /// <remarks>
        /// zur Vereinfachten Anlieferung von Land, Serie und Nr-Von und Bis
        /// </remarks>
        [Column("ZA_IV_EXT")]
        public string? ZA_IV_EXT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zahlunganspruchs-Nummer Obergrenze des Intervalls".
        /// </summary>
        /// <remarks>
        /// Intervallobergrenze innerhalb der Serie als 2. Teil der Identifikation eines Intervalls
        /// </remarks>
        [Column("ZA_NR_BIS")]
        [Required]
        public Int64? ZA_NR_BIS { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Paket-Identifikation mit Land und Serie".
        /// </summary>
        /// <remarks>
        /// zur Vereinfachten Darstellung von Paket-Land, und -Serie
        /// </remarks>
        [Column("ZA_P_EXT")]
        public string? ZA_P_EXT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zahlunganspruchs-Nummer Untergrenze des Intervalls".
        /// </summary>
        /// <remarks>
        /// Intervalluntergrenze innerhalb der Serie als 2. Teil der Identifikation eines Intervalls
        /// </remarks>
        [Column("ZA_NR_VON")]
        [Required]
        public Int64? ZA_NR_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ende der Gültigkeit der Paketzugehörigkeit".
        /// </summary>
        /// <remarks>
        /// erste Mikrosekunde an dem ZA nicht mehr zum Paket gehört, damit ggf. identisch mit nächstem Beginn
        /// </remarks>
        [Column("ZA_PK_BIS")]
        [Required]
        public DateTime? ZA_PK_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zahlunganspruchs-Serie".
        /// </summary>
        /// <remarks>
        /// Seriennummer des Zahlungsanspruchs als 1. Teil der Identifikation
        /// </remarks>
        [Column("ZA_SERIE")]
        [Required]
        public Int64? ZA_SERIE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Beginn der Gültigkeit der Paketzugehörigkeit".
        /// </summary>
        /// <remarks>
        /// erste Mikrosekunde an dem der ZA zum Paket zugehörig ist.
        /// </remarks>
        [Column("ZA_PK_VON")]
        [Required]
        public DateTime? ZA_PK_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Paket-Land".
        /// </summary>
        /// <remarks>
        /// Land das das Paket ausgegeben hat. Dient mit Serie zur Identifikation.
        /// </remarks>
        [Column("ZA_P_LAND")]
        [Required]
        public int? ZA_P_LAND { get; set; }

        /// <summary>
        /// Gets or sets the value of "Paket-GVE".
        /// </summary>
        [Column("ZA_PK_GVE")]
        [Required]
        public decimal? ZA_PK_GVE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Paket-Serie".
        /// </summary>
        /// <remarks>
        /// Seriennummer des Pakets, aus den ursprünglichen Entstehungs-ZA
        /// </remarks>
        [Column("ZA_P_SERIE")]
        [Required]
        public Int64? ZA_P_SERIE { get; set; }

    }
}
