// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Zahlungsansprüche, Zeitattribut
    /// </summary>
    [Entity("ZA_ZEITATR")]
    public class ZA_ZEITATR
    {
        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zahlunganspruchs-Nummer Obergrenze des Intervalls".
        /// </summary>
        /// <remarks>
        /// Intervallobergrenze innerhalb der Serie als 2. Teil der Identifikation eines Intervalls
        /// </remarks>
        [Column("ZA_NR_BIS")]
        [Required]
        public Int64? ZA_NR_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Beginn der Gültigkeit des Zeitwertes".
        /// </summary>
        /// <remarks>
        /// erste Mikrosekunde an dem der neue Zeitwert gültig ist
        /// </remarks>
        [Column("ZA_ZW_VON")]
        [Required]
        public DateTime? ZA_ZW_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zahlunganspruchs-Nummer Untergrenze des Intervalls".
        /// </summary>
        /// <remarks>
        /// Intervalluntergrenze innerhalb der Serie als 2. Teil der Identifikation eines Intervalls
        /// </remarks>
        [Column("ZA_NR_VON")]
        [Required]
        public Int64? ZA_NR_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Grund der Änderung des Zeitwertes".
        /// </summary>
        [Column("ZA_ZW_AEN")]
        [Required]
        public int? ZA_ZW_AEN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zahlunganspruchs-Serie".
        /// </summary>
        /// <remarks>
        /// Seriennummer des Zahlungsanspruchs als 1. Teil der Identifikation
        /// </remarks>
        [Column("ZA_SERIE")]
        [Required]
        public Int64? ZA_SERIE { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zeitwert des Zahlungsanspruchs".
        /// </summary>
        /// <remarks>
        /// Wert in Euro mit 2 Nachkommastellen (damit auf Cent genau)
        /// </remarks>
        [Column("ZA_ZWERT")]
        [Required]
        public decimal? ZA_ZWERT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Liegt besondere Kennzeichnung als Obst - Gemüse - Speisekartoffel vor".
        /// </summary>
        /// <remarks>
        /// Berechtigt zur Aktivierung mit OGS-Flächen
        /// </remarks>
        [Column("ZA_OGS")]
        [Required]
        public bool? ZA_OGS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Ende der Gültigkeit des Zeitwertes".
        /// </summary>
        /// <remarks>
        /// erste Mikrosekunde an dem Zeitwert nicht mehr gültig ist, damit ggf. identisch mit nächstem Beginn
        /// </remarks>
        [Column("ZA_ZW_BIS")]
        [Required]
        public DateTime? ZA_ZW_BIS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betrag aus Nationaler Reserve".
        /// </summary>
        /// <remarks>
        /// ist auch im Wert des ZA enthalten, bedeutet damit davon
        /// </remarks>
        [Column("ZA_AUS_NR")]
        [Required]
        public decimal? ZA_AUS_NR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Art des Zahlungsanspruchs".
        /// </summary>
        /// <remarks>
        /// Art gemäß der Entstehung als AL, DGL, BES, STL
        /// </remarks>
        [Column("ZA_ART")]
        [Required]
        public int? ZA_ART { get; set; }

        /// <summary>
        /// Gets or sets the value of "Art des Zahlungsanspruchs bezüglich NR".
        /// </summary>
        /// <remarks>
        /// Urpsüngl. Ausgabeart ohne NR, bis 20% oder mehr als 20% kann sich im Zeitablauf ändern
        /// </remarks>
        [Column("ZA_ART_NR")]
        [Required]
        public int? ZA_ART_NR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zahlungsanspruchs-Land".
        /// </summary>
        /// <remarks>
        /// Land das den ZA ausgegeben hat. Dient mit Serie und Nr zur Identifikation.
        /// </remarks>
        [Column("ZA_LAND")]
        [Required]
        public int? ZA_LAND { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zucker-Erhöhung 2006".
        /// </summary>
        /// <remarks>
        /// vorgenommene Erhöhung des Wertes in 2006, bzw. für nachträglich ausgegebene 1.Erhöhung
        /// </remarks>
        [Column("ZA_ZU_06")]
        public decimal? ZA_ZU_06 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Zahlunganspruchsintervall, externe Darstellung".
        /// </summary>
        /// <remarks>
        /// zur Vereinfachten Anlieferung von Land, Serie und Nr-Von und Bis
        /// </remarks>
        [Column("ZA_IV_EXT")]
        public string? ZA_IV_EXT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Tabak-Erhöhung 2006".
        /// </summary>
        /// <remarks>
        /// In 2006 vorgenommene Erhöhung des Wertes
        /// </remarks>
        [Column("ZA_TB_06")]
        public decimal? ZA_TB_06 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Angabe ob Milcherhöhung bereits durchgeführt".
        /// </summary>
        [Column("ZA_ME_DONE")]
        public bool? ZA_ME_DONE { get; set; }

    }
}
