// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Zahlungsansprüche V2, Nutzung
    /// </summary>
    [Entity("ZB_NUTZUNG")]
    public class ZB_NUTZUNG
    {
        /// <summary>
        /// Gets or sets the value of "Globally Unique Identifier".
        /// </summary>
        /// <remarks>
        /// Format xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (lower case)
        /// </remarks>
        [Column("GUID")]
        public string? GUID { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "ZA-Nutzungsart".
        /// </summary>
        /// <remarks>
        /// Normale Nutzung oder Pseudo-Nutzung
        /// </remarks>
        [Column("ZB_NU_ART")]
        [Required]
        public int? ZB_NU_ART { get; set; }

        /// <summary>
        /// Gets or sets the value of "ZA-Nutzung Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer der Person bzw. InVeKoS / Unternehmen
        /// </remarks>
        [Column("ZB_NU_BNR")]
        [Required]
        public decimal? ZB_NU_BNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Jahr der ZA-Nutzung".
        /// </summary>
        /// <remarks>
        /// Jahresangabe, vierstellig
        /// </remarks>
        [Column("ZB_NU_JAHR")]
        [Required]
        public int? ZB_NU_JAHR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nutzungsumfang".
        /// </summary>
        /// <remarks>
        /// auf Basis ganzer ZA mit Nachkomma
        /// </remarks>
        [Column("ZB_NU_UMF")]
        [Required]
        public decimal? ZB_NU_UMF { get; set; }

        /// <summary>
        /// Gets or sets the value of "Region des Bewirtschaftungslandes".
        /// </summary>
        /// <remarks>
        /// Region der Belegenheit der Fläche die den ZA begründet hat
        /// </remarks>
        [Column("ZB_REG_FL")]
        [Required]
        public int? ZB_REG_FL { get; set; }

    }
}
