// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Zirkusregister Vorort Kontrolle Auflagen-Erfüllung
    /// </summary>
    [Entity("ZR_VOKE")]
    public class ZR_VOKE
    {
        /// <summary>
        /// Gets or sets the value of "Zirkus Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer des Zirkusbetriebes
        /// </remarks>
        [Column("ZR_BNR15")]
        [Required]
        public decimal? ZR_BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Datum der Vorortkontrolle".
        /// </summary>
        [Column("ZR_VOK_DAT")]
        [Required]
        public DateOnly? ZR_VOK_DAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Laufende Nummer Feststellung".
        /// </summary>
        [Column("ZR_VF_LNR")]
        [Required]
        public Int64? ZR_VF_LNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Datum der Überprüfung der Maßnahmenerfüllung".
        /// </summary>
        [Column("ZR_VE_DAT")]
        [Required]
        public DateOnly? ZR_VE_DAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Status Maßnahmenerfüllung".
        /// </summary>
        [Column("ZR_VE_STAT")]
        [Required]
        public int? ZR_VE_STAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Bemerkung zur Maßnahmenerfüllung".
        /// </summary>
        [Column("ZR_VE_BEM")]
        [Required]
        public string? ZR_VE_BEM { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Stornobetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_BNR")]
        public decimal? STRN_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Stornomitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung storniert hat
        /// </remarks>
        [Column("STRN_MBN")]
        public int? STRN_MBN { get; set; }

    }
}
