// 
// This file has been auto-generated by Esstra.Hit.Client.CodeGen.
// 
namespace Esstra.Hit.Client.Entities
{
    using Esstra.Hit.Client.Annotations;

    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Text.Json.Serialization;

    /// <summary>
    /// Anträge
    /// </summary>
    [Entity("ZS_ANTRAG")]
    public class ZS_ANTRAG
    {
        /// <summary>
        /// Gets or sets the value of "Antragsmaßnahme für Antragstellerabgleich".
        /// </summary>
        [Column("ANTR_MAS")]
        [Required]
        public int? ANTR_MAS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Antragsteller-Mitbenutzer".
        /// </summary>
        /// <remarks>
        /// Meldemitbenutzer des zuständigen Mitarbeiters
        /// </remarks>
        [Column("AN_AMT_MBN")]
        [Required]
        public int? AN_AMT_MBN { get; set; }

        /// <summary>
        /// Gets or sets the value of "Antragsteller-Amt".
        /// </summary>
        /// <remarks>
        /// Registriernummer des zuständigen Amtes
        /// </remarks>
        [Column("AN_AMT_BNR")]
        [Required]
        public decimal? AN_AMT_BNR { get; set; }

        /// <summary>
        /// Gets the value of "Meldemitbenutzer".
        /// </summary>
        /// <remarks>
        /// Mitbenutzernummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_MBN")]
        public int? MELD_MBN { get; set; }

        /// <summary>
        /// Gets the value of "Satzstatus".
        /// </summary>
        /// <remarks>
        /// Systemstatus des Satzes
        /// </remarks>
        [Column("SYS_STAT")]
        public int? SYS_STAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Lokaler Bearbeitungsstand".
        /// </summary>
        /// <remarks>
        /// Zeitpunkt der letzten lokalen Bearbeitung
        /// </remarks>
        [Column("PR_LOK_TS")]
        public DateTime? PR_LOK_TS { get; set; }

        /// <summary>
        /// Gets or sets the value of "Prämienantragnummer".
        /// </summary>
        /// <remarks>
        /// Nummer des Antrag, mit 01..16 für Land am Anfang
        /// </remarks>
        [Column("PR_ANTR_NR")]
        [Required]
        public string? PR_ANTR_NR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Jahr".
        /// </summary>
        /// <remarks>
        /// Jahresangabe, vierstellig
        /// </remarks>
        [Column("JAHR")]
        [Required]
        public int? JAHR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geburts- oder Gründungsdatum Antragsteller".
        /// </summary>
        [Column("ANTS_GDAT")]
        public DateOnly? ANTS_GDAT { get; set; }

        /// <summary>
        /// Gets or sets the value of "Betriebsnummer".
        /// </summary>
        /// <remarks>
        /// Registriernummer für Betrieb, Langform mit B.Land und Staat
        /// </remarks>
        [Column("BNR15")]
        [Required]
        public decimal? BNR15 { get; set; }

        /// <summary>
        /// Gets or sets the value of "Abgleichzeitpunkt ggf. fachliche Gültigkeit".
        /// </summary>
        /// <remarks>
        /// Abgleich mit Betriebsstammdaten zu dieser fachlichen Gültigkeit, oder NULL kein Abgleich
        /// </remarks>
        [Column("ANTR_TS")]
        public DateTime? ANTR_TS { get; set; }

        /// <summary>
        /// Gets the value of "gespeichert".
        /// </summary>
        /// <remarks>
        /// Speichern-Zeitpunkt, ab wann die Information technisch gültig ist
        /// </remarks>
        [Column("SYS_VON")]
        public DateTime? SYS_VON { get; set; }

        /// <summary>
        /// Gets or sets the value of "Antragstellername".
        /// </summary>
        /// <remarks>
        /// bei nat. Person - Nachname Vorname, bei jur. Person - Eingetragene Bezeichnung
        /// </remarks>
        [Column("ANTS_NAME")]
        public string? ANTS_NAME { get; set; }

        /// <summary>
        /// Gets the value of "Meldebetrieb".
        /// </summary>
        /// <remarks>
        /// Betriebsnummer die Meldung abgesetzt hat
        /// </remarks>
        [Column("MELD_BNR")]
        public decimal? MELD_BNR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Nummer zur Differenzierung oder Identifizierung von Antragsteller".
        /// </summary>
        /// <remarks>
        /// wenn Name, Datum und Ort keine Unterscheidung zulassen, in Absprache mit Amt des Konfliktpartner
        /// </remarks>
        [Column("ANTS_NR")]
        public Int64? ANTS_NR { get; set; }

        /// <summary>
        /// Gets or sets the value of "Geburts- oder Gründungsort Antragsteller".
        /// </summary>
        /// <remarks>
        /// exakt wie im Pass, Ausweis oder Gründungsdokument angegeben
        /// </remarks>
        [Column("ANTS_GORT")]
        public string? ANTS_GORT { get; set; }

        /// <summary>
        /// Gets the value of "storniert".
        /// </summary>
        /// <remarks>
        /// Storno-Zeitpunkt, ab wann die Information technisch nicht meht gültig ist
        /// </remarks>
        [Column("SYS_BIS")]
        public DateTime? SYS_BIS { get; set; }

        /// <summary>
        /// Gets the value of "Systematischer Antragstellername".
        /// </summary>
        [Column("SYS_NAME_A")]
        public string? SYS_NAME_A { get; set; }

        /// <summary>
        /// Gets or sets the value of "Antragstellertyp, natürliche oder juristische Pers".
        /// </summary>
        [Column("ANTS_TYP")]
        [Required]
        public int? ANTS_TYP { get; set; }

    }
}
